import type { Lesson } from './lessons'
import type { QuizQuestion } from './quizzes'

function lesson(id: string, subject: string, category: string, title: string, objectiveEn: string, objectiveTa: string, explanation: string, examples: string[], summary: string, order: number): Lesson {
  return { id, subject, category, title, objectives: [objectiveEn, objectiveTa], explanation: `${explanation} தமிழ்: ${objectiveTa}`, examples, summary, difficulty: 'intermediate', duration: 25, order }
}
function mcq(id: string, subject: string, lessonId: string, question: string, options: string[], correctAnswer: number, explanation: string): QuizQuestion {
  return { id, subject, lessonId, type: 'mcq', question, options, correctAnswer, explanation, difficulty: 'medium' }
}
function short(id: string, subject: string, lessonId: string, question: string, correctAnswer: string, explanation: string): QuizQuestion {
  return { id, subject, lessonId, type: 'short-answer', question, correctAnswer, explanation, difficulty: 'medium' }
}

export const kvsPrerequisiteLessons: Lesson[] = [
  lesson('KVS-MATH-A07-L04-DIV-001','Mathematics','Number','Understand Division by Sharing and Grouping','Represent division as equal sharing and equal grouping, connect it to multiplication facts, and interpret simple remainders in context.','வகுத்தலை சமமாகப் பகிர்தல் மற்றும் சமக் குழுக்களாக்கல் என பிரதிநிதித்துவப்படுத்தி, பெருக்கல் உண்மைகளுடன் இணைத்து, எளிய மீதிகளை சூழலுக்கு ஏற்ப விளக்குதல்.','12 shared equally among 3 groups gives 4 in each group: 12 ÷ 3 = 4. 12 arranged in groups of 4 makes 3 groups: 12 ÷ 4 = 3.',['Use 15 counters to make 5 equal groups, giving 3 in each.'],'Division can represent equal sharing or equal grouping and connects directly to multiplication facts.',401),
  lesson('KVS-TAM-A09-L03-POS-001','Tamil','இலக்கணம்','பெயர்ச்சொல் மற்றும் வினைச்சொல்லை வேறுபடுத்துவோம்','Identify common nouns and verbs in simple Tamil sentences and use their roles to build clearer sentences.','எளிய தமிழ் வாக்கியங்களில் பொதுவான பெயர்ச்சொல் மற்றும் வினைச்சொற்களை அடையாளம் கண்டு, அவற்றின் பங்கைப் பயன்படுத்தி தெளிவான வாக்கியங்களை அமைத்தல்.','பெயர்ச்சொல் ஒருவரை, இடத்தை, பொருளை அல்லது கருத்தை பெயரிட்டு குறிப்பிடலாம். வினைச்சொல் செயல் அல்லது நிகழ்வை காட்டுகிறது. ஒரே சொல் சூழலைப் பொறுத்து வேறு இலக்கணப் பங்கு பெறக்கூடும்; வாக்கியத்தில் அதன் பங்கை பார்க்க வேண்டும்.',['“மாணவி புத்தகம் படிக்கிறாள்.” — மாணவி/புத்தகம் பெயர்ச்சொற்கள்; படிக்கிறாள் வினைச்சொல்.'],'சொல்லின் இலக்கணப் பங்கை வாக்கியச் சூழலில் பார்த்து பெயர்ச்சொல் மற்றும் வினைச்சொல்லை வேறுபடுத்த வேண்டும்.',402),
  lesson('KVS-ENG-A13-L02-INFER-001','English','Reading','Infer Meaning and Analyse Word Choice','Make a justified inference from textual evidence and explain how a specific word or phrase shapes tone or emphasis.','உரை ஆதாரத்தைப் பயன்படுத்தி நியாயமான மறைமுக முடிவை உருவாக்கி, குறிப்பிட்ட சொல் அல்லது சொற்றொடர் தொனி/வலியுறுத்தலை எவ்வாறு மாற்றுகிறது என்பதை விளக்குதல்.','An inference combines text evidence with reasonable background knowledge. A strong inference can point to specific words or details that support it. Word choice can influence tone, intensity and reader impression.',['“Maya checked the clock for the third time and tapped her foot.” → infer impatience, citing the repeated clock-check and tapping.'],'Strong inference is evidence-based and uses appropriately qualified analytical language.',403),
  lesson('KVS-CT-A09-L02-DEBUG-001','Coding','Programming Concepts','Debug an Algorithm Step by Step','Trace a short sequence/conditional algorithm, distinguish wording/syntax-like problems from logic errors conceptually, and make the smallest justified fix.','குறுகிய வரிசை/நிபந்தனை அல்கோரிதத்தைப் பின்தொடர்ந்து, சொல்லாக்கப் பிழை மற்றும் தர்க்கப் பிழையை கருத்தியல் ரீதியில் வேறுபடுத்தி, தேவையான குறைந்த மாற்றத்தைச் செய்தல்.','Debugging means finding and fixing the cause of incorrect behaviour, not randomly changing many things. Tracing records state or decisions step by step, and boundary test cases help expose logic errors.',['Rule: if score >= 10 say “win”; test score 10 to catch an incorrect > 10 boundary.'],'Trace, compare expected and actual results, then make small evidence-based fixes.',404),
  lesson('KVS-MATH-A13-L03-PYTHAG-001','Mathematics','Geometry','Use Pythagoras’ Theorem in Right Triangles','Use a² + b² = c² for right triangles, identify the hypotenuse correctly, and check whether a triple of side lengths can form a right triangle.','செங்கோண முக்கோணங்களில் a² + b² = c² ஐப் பயன்படுத்தி, கர்ணத்தை சரியாக அடையாளம் கண்டு, கொடுக்கப்பட்ட பக்க நீளங்கள் செங்கோண முக்கோணமாக அமையுமா எனச் சரிபார்த்தல்.','In a right triangle, the hypotenuse is opposite the right angle and is the longest side. For the two shorter sides a and b and hypotenuse c, a² + b² = c². The relationship applies specifically to right triangles.',['3² + 4² = 9 + 16 = 25 = 5², so a 3-4-5 triangle is right-angled.'],'Identify the right angle and hypotenuse before applying a² + b² = c².',405),
  lesson('KVS-SCI-A11-L04-FORCE-001','Science','Physics','Reason About Balanced and Unbalanced Forces','Use force arrows in simplified one-dimensional situations to determine resultant force and predict whether motion can change.','எளிய ஒரே திசை நிலைகளில் விசை அம்புகளைப் பயன்படுத்தி நிகர விசையை கண்டறிந்து, இயக்கம் மாறுமா என கணித்தல்.','Forces have size and direction. In a simplified one-dimensional model, equal opposing forces give zero resultant force. Zero resultant force does not require the object to be stationary; it means there is no change in velocity in the model.',['5 N right and 5 N left give a resultant of 0 N.'],'Force arrows need both size and direction; balanced forces give zero resultant force.',406),
]

export const kvsPrerequisiteQuizzes: QuizQuestion[] = [
  mcq('KVS-Q-MATH-A07-DIV-00001','Mathematics','KVS-MATH-A07-L04-DIV-001','18 counters are shared equally among 3 groups. How many are in each group? — 18 கற்கள் 3 குழுக்களில் சமமாகப் பகிரப்படுகின்றன. ஒவ்வொரு குழுவிலும் எத்தனை?',['5','6','7'],1,'18 ÷ 3 = 6.'),
  short('KVS-Q-MATH-A07-DIV-00002','Mathematics','KVS-MATH-A07-L04-DIV-001','How does 5 × 4 = 20 help solve 20 ÷ 4? — 5 × 4 = 20 என்பது 20 ÷ 4 ஐ எவ்வாறு தீர்க்க உதவுகிறது?','It shows that 20 contains 5 groups of 4, so 20 ÷ 4 = 5.','Multiplication and division use the same fact-family relationship.'),
  mcq('KVS-Q-MATH-A07-DIV-00003','Mathematics','KVS-MATH-A07-L04-DIV-001','14 stickers are shared equally between 4 children. Which statement is most accurate if stickers cannot be split? — 14 ஸ்டிக்கர்கள் 4 குழந்தைகளுக்கு சமமாகப் பகிரப்படுகின்றன. ஸ்டிக்கரைப் பிரிக்க முடியாவிட்டால் எது சரி?',['Each gets 3, with 2 stickers left over.','Each gets 4 with none left.','Each gets exactly 3 and nothing remains.'],0,'4 × 3 = 12, leaving a remainder of 2.'),
  short('KVS-Q-MATH-A07-DIV-00004','Mathematics','KVS-MATH-A07-L04-DIV-001','“24 ÷ 6 = 4, so 24 ÷ 4 must also equal 4.” What is the error? — “24 ÷ 6 = 4; ஆகவே 24 ÷ 4 கூட 4” என்ற கூற்றில் பிழை என்ன?','Changing the divisor changes the number or size of groups; 24 ÷ 4 = 6.','The related multiplication facts are 6 × 4 = 24 and 4 × 6 = 24.'),
  mcq('KVS-Q-TAM-A09-POS-00001','Tamil','KVS-TAM-A09-L03-POS-001','“குமார் ஓடுகிறான்” என்ற வாக்கியத்தில் வினைச்சொல் எது? — In “குமார் ஓடுகிறான்”, which word is the verb?',['குமார்','ஓடுகிறான்'],1,'“ஓடுகிறான்” செயலைக் காட்டுகிறது.'),
  mcq('KVS-Q-TAM-A09-POS-00002','Tamil','KVS-TAM-A09-L03-POS-001','“மலர் மேசையில் உள்ளது” என்ற வாக்கியத்தில் பொருளின் பெயரை தெளிவாகக் காட்டுவது எது? — Which word most clearly names an object?',['மலர்','உள்ளது'],0,'“மலர்” ஒரு பொருளை பெயரிட்டு குறிப்பிடுகிறது.'),
  short('KVS-Q-TAM-A09-POS-00003','Tamil','KVS-TAM-A09-L03-POS-001','“வாக்கியத்தில் ஒரு மனிதர் பெயர் இருந்தால் மற்ற பெயர்ச்சொற்கள் இருக்க முடியாது” என்ற கூற்றில் பிழை என்ன?','ஒரே வாக்கியத்தில் பல பெயர்ச்சொற்கள் இருக்கலாம்.','மனிதர், பொருள், இடம் போன்ற பல பெயர்கள் ஒரே வாக்கியத்தில் வரலாம்.'),
  short('KVS-Q-TAM-A09-POS-00004','Tamil','KVS-TAM-A09-L03-POS-001','“பூனை பாலை குடிக்கிறது” என்ற வாக்கியத்தில் “பூனை” மற்றும் “குடிக்கிறது” ஏன் வேறு சொல்வகைகள்?','“பூனை” ஒன்றை பெயரிட்டு குறிப்பிடுகிறது; “குடிக்கிறது” செயலைக் காட்டுகிறது.','சொற்களின் வாக்கியப் பங்கு அவற்றின் சொல்வகையைத் தெளிவாக்குகிறது.'),
  mcq('KVS-Q-ENG-A13-INFER-00001','English','KVS-ENG-A13-L02-INFER-001','Text: “Arun read the message twice, then quietly put his phone face-down.” Which inference is best supported? — எந்த மறைமுக முடிவு சிறப்பாக ஆதரிக்கப்படுகிறது?',['The message affected Arun enough for him to pause or withdraw, but the exact emotion is uncertain.','Arun is definitely furious.','Arun did not read the message.'],0,'The actions support a reaction, but they do not prove a specific emotion such as anger or sadness.'),
  mcq('KVS-Q-ENG-A13-INFER-00002','English','KVS-ENG-A13-L02-INFER-001','Which sentence contains the stronger word choice for difficulty? — சிரமத்தை அதிகமாக உணர்த்தும் சொல் தேர்வு எந்த வாக்கியத்தில் உள்ளது?',['She struggled up the hill.','She walked up the hill.'],0,'“Struggled” suggests greater effort than the neutral “walked.”'),
  short('KVS-Q-ENG-A13-INFER-00003','English','KVS-ENG-A13-L02-INFER-001','“The character closed the door, so we know exactly what she was thinking.” What is the error?','An action may support several interpretations; the exact thought needs stronger evidence.','Inference should be proportional to the evidence.'),
  short('KVS-Q-ENG-A13-INFER-00004','English','KVS-ENG-A13-L02-INFER-001','Why is “This suggests…” often stronger analytical wording than “This proves…” when interpreting a fictional detail?','Interpretive evidence often supports a plausible reading without proving it uniquely.','Qualified language matches the uncertainty of interpretation.'),
  mcq('KVS-Q-CT-A09-DEBUG-00001','Coding','KVS-CT-A09-L02-DEBUG-001','Rule: IF number > 5 output “high”, ELSE output “low”. What should input 5 output? — உள்ளீடு 5 என்றால் வெளியீடு என்ன?',['low','high'],0,'5 is not greater than 5, so the ELSE branch runs.'),
  short('KVS-Q-CT-A09-DEBUG-00002','Coding','KVS-CT-A09-L02-DEBUG-001','A learner changes five lines after one test fails. Why is this poor debugging practice?','Changing many things at once makes it harder to know which change fixed or caused behaviour.','Small, evidence-based changes make cause and effect easier to trace.'),
  mcq('KVS-Q-CT-A09-DEBUG-00003','Coding','KVS-CT-A09-L02-DEBUG-001','Which test is especially useful for rule “score >= 10”?',['score = 10','score = 1000 only','no test'],0,'Testing the boundary value checks whether >= was implemented correctly.'),
  short('KVS-Q-CT-A09-DEBUG-00004','Coding','KVS-CT-A09-L02-DEBUG-001','Why should a test case record both expected and actual output?','The comparison shows whether behaviour matches the requirement and helps locate failures.','Without an expected result, “worked” has no clear reference.'),
  mcq('KVS-Q-MATH-A13-PYTHAG-00001','Mathematics','KVS-MATH-A13-L03-PYTHAG-001','In a right triangle, which side is the hypotenuse? — செங்கோண முக்கோணத்தில் கர்ணம் எது?',['The side opposite the right angle.','Any shortest side','The side touching every angle'],0,'The hypotenuse lies opposite the 90° angle.'),
  mcq('KVS-Q-MATH-A13-PYTHAG-00002','Mathematics','KVS-MATH-A13-L03-PYTHAG-001','A right triangle has shorter sides 6 and 8. What is the hypotenuse? — கர்ணம் எவ்வளவு?',['10','14','7'],0,'6² + 8² = 36 + 64 = 100, so c = 10.'),
  short('KVS-Q-MATH-A13-PYTHAG-00003','Mathematics','KVS-MATH-A13-L03-PYTHAG-001','“The sides are 2, 3 and 4, so 2² + 3² must equal 4² because 4 is longest.” What is wrong?','Being the longest side does not guarantee a right triangle; 4 + 9 ≠ 16.','The equation must be checked; it is not true for every triangle.'),
  short('KVS-Q-MATH-A13-PYTHAG-00004','Mathematics','KVS-MATH-A13-L03-PYTHAG-001','Why must you identify the right angle before deciding which side is c?','c is defined as the side opposite the right angle, not simply by how the diagram is drawn.','Diagrams can be rotated; the right-angle relationship determines the hypotenuse.'),
  mcq('KVS-Q-SCI-A11-FORCE-00001','Science','KVS-SCI-A11-L04-FORCE-001','A box has 8 N to the right and 3 N to the left. What is the resultant force? — நிகர விசை எவ்வளவு?',['5 N to the right','11 N to the right','5 N to the left'],0,'Opposite forces subtract: 8 − 3 = 5 N toward the larger force.'),
  mcq('KVS-Q-SCI-A11-FORCE-00002','Science','KVS-SCI-A11-L04-FORCE-001','Two equal forces act in opposite directions on an object. What is the resultant force?',['0 N','Twice one force','Always 1 N'],0,'Equal opposite forces cancel in the resultant.'),
  short('KVS-Q-SCI-A11-FORCE-00003','Science','KVS-SCI-A11-L04-FORCE-001','“Resultant force is zero, so the object must be standing still.” What is the error?','Zero resultant means no acceleration in this simplified model; the object could also be moving at constant velocity.','Balanced forces do not require zero velocity.'),
  short('KVS-Q-SCI-A11-FORCE-00004','Science','KVS-SCI-A11-L04-FORCE-001','Why should force arrows include direction as well as size?','Forces in opposite directions combine differently from forces in the same direction.','Direction is necessary to calculate the resultant correctly.'),
]
