import type { Lesson } from './lessons'
import type { QuizQuestion } from './quizzes'

export const kvsEnglishLessons: Lesson[] = [
  {
    id: "KVS-ENG-A09-L03-VOCAB-001",
    subject: "English",
    category: "Vocabulary in Context",
    title: "Work Out Meaning From Context",
    objectives: ["Use surrounding sentences, examples and familiar word parts to infer a plausible word meaning, then check that meaning against the whole passage.", "சுற்றியுள்ள வாக்கியங்கள், எடுத்துக்காட்டுகள் மற்றும் அறிந்த சொல் கூறுகளைப் பயன்படுத்தி ஒரு ஆங்கிலச் சொல்லின் சாத்தியமான பொருளை ஊகித்து, முழுப் பகுதியுடன் சரிபார்த்தல்."],
    explanation: "Context clues can include definitions, examples, contrasts and consequences. Prefixes/suffixes can help, but context confirms meaning. A good inferred meaning must make sense in the entire sentence or paragraph. Do not choose a meaning only because one nearby word looks similar. தமிழ்: சுற்றியுள்ள வாக்கியங்கள், எடுத்துக்காட்டுகள் மற்றும் அறிந்த சொல் கூறுகளைப் பயன்படுத்தி ஒரு ஆங்கிலச் சொல்லின் சாத்தியமான பொருளை ஊகித்து, முழுப் பகுதியுடன் சரிபார்த்தல்.",
    examples: ["“The path was treacherous; it was icy and several walkers slipped.” → treacherous likely means dangerous.", "Underline context clues before suggesting a meaning."],
    summary: "Do not choose a meaning only because one nearby word looks similar.",
    difficulty: "intermediate",
    duration: 25,
    order: 101,
  },
  {
    id: "KVS-ENG-A11-L03-CLAUSE-001",
    subject: "English",
    category: "Clauses",
    title: "Build Sentence Variety With Clauses",
    objectives: ["Distinguish independent and dependent clauses and combine them to create clear, varied sentences with appropriate punctuation.", "தனி முழு clause மற்றும் சார்பு clause-ஐ வேறுபடுத்தி, பொருத்தமான நிறுத்தக்குறிகளுடன் தெளிவான பல்வகை வாக்கியங்களை உருவாக்குதல்."],
    explanation: "An independent clause can stand as a complete sentence. A dependent clause does not express a complete thought on its own. Clause order can change emphasis while preserving meaning. Punctuation depends on sentence structure; avoid comma splices between independent clauses. தமிழ்: தனி முழு clause மற்றும் சார்பு clause-ஐ வேறுபடுத்தி, பொருத்தமான நிறுத்தக்குறிகளுடன் தெளிவான பல்வகை வாக்கியங்களை உருவாக்குதல்.",
    examples: ["Because the rain stopped, we continued the match.", "We continued the match because the rain stopped.", "Label clauses, then combine them in two valid ways."],
    summary: "Punctuation depends on sentence structure; avoid comma splices between independent clauses.",
    difficulty: "intermediate",
    duration: 25,
    order: 102,
  },
  {
    id: "KVS-ENG-A13-L03-COHESION-001",
    subject: "English",
    category: "Cohesion and Precision",
    title: "Make Paragraphs Cohesive and Precise",
    objectives: ["Improve paragraph cohesion by using logical links, reference words and precise vocabulary without overusing formulaic connectors.", "தர்க்க ரீதியான இணைப்புகள், குறிப்பு சொற்கள் மற்றும் துல்லியமான சொற்களஞ்சியத்தைப் பயன்படுத்தி, இயந்திரமாக இணைப்புச் சொற்களை மிகைப்படுத்தாமல் பதிவின் தொடர்பை மேம்படுத்துதல்."],
    explanation: "Cohesion comes from clear idea relationships, not from inserting connectors everywhere. Pronouns/reference words must have clear antecedents. Precise verbs and nouns can reduce vague wording. A connector should match the logical relationship: contrast, cause, addition, example or conclusion. தமிழ்: தர்க்க ரீதியான இணைப்புகள், குறிப்பு சொற்கள் மற்றும் துல்லியமான சொற்களஞ்சியத்தைப் பயன்படுத்தி, இயந்திரமாக இணைப்புச் சொற்களை மிகைப்படுத்தாமல் பதிவின் தொடர்பை மேம்படுத்துதல்.",
    examples: ["Replace “This is good. Also this helps.” with a precise cause/effect link when the second idea is a consequence.", "Choose between however, therefore, for example and additionally based on meaning."],
    summary: "A connector should match the logical relationship: contrast, cause, addition, example or conclusion.",
    difficulty: "intermediate",
    duration: 25,
    order: 103,
  },
]

export const kvsEnglishQuizzes: QuizQuestion[] = [
  {
    id: "KVS-Q-ENG-A09-VOCAB-00001",
    subject: "English",
    lessonId: "KVS-ENG-A09-L03-VOCAB-001",
    type: "mcq",
    question: "“The trail was treacherous; ice covered the rocks and two hikers slipped.” What does treacherous most likely mean? — “The trail was treacherous; ice covered the rocks and two hikers slipped.” இங்கு treacherous என்பதன் சாத்தியமான பொருள் என்ன?",
    options: ["dangerous", "tiny", "colourful"],
    correctAnswer: 0,
    explanation: "The consequences and icy rocks provide context clues for danger. தமிழ்: பனியும் வழுக்கலும் ஆபத்தைக் குறிக்கும் சூழல் குறிப்புகள்.",
    difficulty: "medium",
  },
  {
    id: "KVS-Q-ENG-A09-VOCAB-00002",
    subject: "English",
    lessonId: "KVS-ENG-A09-L03-VOCAB-001",
    type: "short-answer",
    question: "A word has the prefix “re-”, but the sentence context does not fit “again”. What should you do? — ஒரு சொல்லில் “re-” உள்ளது; ஆனால் “again” என்ற பொருள் சூழலுக்கு பொருந்தவில்லை. என்ன செய்ய வேண்டும்?",
    correctAnswer: "Use the whole word and sentence context rather than forcing a prefix meaning.",
    explanation: "Word parts help, but context must confirm the interpretation. தமிழ்: சொல் கூறுகள் உதவினாலும், முழுச் சூழல் பொருளை உறுதி செய்ய வேண்டும்.",
    difficulty: "medium",
  },
  {
    id: "KVS-Q-ENG-A09-VOCAB-00003",
    subject: "English",
    lessonId: "KVS-ENG-A09-L03-VOCAB-001",
    type: "mcq",
    question: "Which is a contrast clue? — எது contrast clue?",
    options: ["“Unlike the noisy hall, the library was tranquil.”", "“The cat is black.”", "“We arrived at noon.”"],
    correctAnswer: 0,
    explanation: "“Unlike” sets up a contrast that helps infer tranquil. தமிழ்: “Unlike” எதிர்மறை ஒப்பீட்டை காட்டுகிறது.",
    difficulty: "medium",
  },
  {
    id: "KVS-Q-ENG-A09-VOCAB-00004",
    subject: "English",
    lessonId: "KVS-ENG-A09-L03-VOCAB-001",
    type: "short-answer",
    question: "What final check should you make after guessing a word’s meaning from one clue? — ஒரு குறிப்பை வைத்து சொல்லின் பொருளை ஊகித்த பின் என்ன இறுதி சரிபார்ப்பு செய்ய வேண்டும்?",
    correctAnswer: "Check whether the meaning makes sense in the whole sentence or passage.",
    explanation: "A plausible inference should fit the larger context. தமிழ்: ஊகித்த பொருள் முழு வாக்கியம்/பகுதியிலும் பொருந்துகிறதா பார்க்க வேண்டும்.",
    difficulty: "medium",
  },
  {
    id: "KVS-Q-ENG-A11-CLAUSE-00001",
    subject: "English",
    lessonId: "KVS-ENG-A11-L03-CLAUSE-001",
    type: "mcq",
    question: "Which is an independent clause? — எது independent clause?",
    options: ["The experiment ended.", "Because the experiment ended", "Although it was late"],
    correctAnswer: 0,
    explanation: "It expresses a complete thought and can stand alone. தமிழ்: இது முழுமையான கருத்தைத் தெரிவித்து தனியாக நிற்க முடியும்.",
    difficulty: "medium",
  },
  {
    id: "KVS-Q-ENG-A11-CLAUSE-00002",
    subject: "English",
    lessonId: "KVS-ENG-A11-L03-CLAUSE-001",
    type: "short-answer",
    question: "“Because the rain stopped.” is written as a complete sentence in a formal paragraph. What is the issue? — “Because the rain stopped.” தனி முழு வாக்கியமாக எழுதப்பட்டுள்ளது. சிக்கல் என்ன?",
    correctAnswer: "It is a dependent-clause fragment unless the context deliberately uses a fragment for effect.",
    explanation: "“Because” creates dependency; formal explanatory writing normally needs a main clause. தமிழ்: “Because” சார்பு clause உருவாக்குகிறது; பொதுவாக main clause தேவை.",
    difficulty: "medium",
  },
  {
    id: "KVS-Q-ENG-A11-CLAUSE-00003",
    subject: "English",
    lessonId: "KVS-ENG-A11-L03-CLAUSE-001",
    type: "mcq",
    question: "Which version correctly combines the ideas? “The rain stopped. We continued the match.” — “The rain stopped. We continued the match.” என்ற இரண்டு கருத்துகளைச் சரியாக இணைக்கும் வடிவம் எது?",
    options: ["Because the rain stopped, we continued the match.", "Because the rain stopped we. Continued the match.", "The rain stopped, we continued the match."],
    correctAnswer: 0,
    explanation: "The dependent clause is joined to a complete main clause with suitable punctuation. தமிழ்: சார்பு clause மற்றும் main clause சரியாக இணைக்கப்பட்டுள்ளன.",
    difficulty: "medium",
  },
  {
    id: "KVS-Q-ENG-A11-CLAUSE-00004",
    subject: "English",
    lessonId: "KVS-ENG-A11-L03-CLAUSE-001",
    type: "short-answer",
    question: "Why might a writer move a dependent clause to the beginning of a sentence? — ஒரு எழுத்தாளர் dependent clause-ஐ வாக்கியத்தின் தொடக்கத்திற்கு ஏன் நகர்த்தலாம்?",
    correctAnswer: "To change emphasis or foreground context while preserving the core relationship.",
    explanation: "Clause order can shape emphasis without necessarily changing the logical relation. தமிழ்: clause வரிசை முக்கியத்துவத்தை மாற்றலாம்; தர்க்கத் தொடர்பு தொடரலாம்.",
    difficulty: "medium",
  },
  {
    id: "KVS-Q-ENG-A13-COHESION-00001",
    subject: "English",
    lessonId: "KVS-ENG-A13-L03-COHESION-001",
    type: "mcq",
    question: "Which connector best signals contrast? — எந்த connector contrast-ஐ காட்டுகிறது?",
    options: ["however", "therefore", "for example"],
    correctAnswer: 0,
    explanation: "“However” commonly signals a contrast or qualification. தமிழ்: “However” பொதுவாக contrast-ஐ குறிக்கிறது.",
    difficulty: "medium",
  },
  {
    id: "KVS-Q-ENG-A13-COHESION-00002",
    subject: "English",
    lessonId: "KVS-ENG-A13-L03-COHESION-001",
    type: "short-answer",
    question: "A paragraph begins every sentence with “Furthermore,” even when ideas show contrast and cause. What is the main problem? — ஒவ்வொரு வாக்கியமும் “Furthermore” என்று தொடங்குகிறது; ஆனால் கருத்துகளில் contrast மற்றும் cause உள்ளன. முக்கிய சிக்கல் என்ன?",
    correctAnswer: "The connectors do not match the logical relationships and become formulaic.",
    explanation: "Cohesion depends on accurate idea relationships, not repeated formal words. தமிழ்: கருத்துத் தொடர்புக்கு பொருந்தாத connector-கள் cohesion-ஐ குறைக்கும்.",
    difficulty: "medium",
  },
  {
    id: "KVS-Q-ENG-A13-COHESION-00003",
    subject: "English",
    lessonId: "KVS-ENG-A13-L03-COHESION-001",
    type: "short-answer",
    question: "A sentence says “This caused it to change,” but the previous paragraph mentions three possible things. What revision is best? — முந்தைய பகுதியில் மூன்று பொருள்கள் இருந்தபோது “This caused it to change” என்று எழுதப்பட்டுள்ளது. சிறந்த திருத்தம் என்ன?",
    correctAnswer: "Name the specific cause and the thing that changed so the reference is clear.",
    explanation: "Ambiguous reference words weaken cohesion. தமிழ்: தெளிவற்ற reference words தொடர்பை குறைக்கும்; குறிப்பிட்ட பெயரை பயன்படுத்த வேண்டும்.",
    difficulty: "medium",
  },
  {
    id: "KVS-Q-ENG-A13-COHESION-00004",
    subject: "English",
    lessonId: "KVS-ENG-A13-L03-COHESION-001",
    type: "short-answer",
    question: "What is more important than using impressive vocabulary in an academic paragraph? — academic paragraph-ல் கவர்ச்சியான சொற்களைப் பயன்படுத்துவதைவிட முக்கியமானது என்ன?",
    correctAnswer: "Using precise words that express the intended meaning accurately.",
    explanation: "Precision and clarity matter more than inflated wording. தமிழ்: துல்லியமும் தெளிவும் பெருமையான சொற்களைவிட முக்கியம்.",
    difficulty: "medium",
  },
]
