import type { Lesson } from './lessons'
import type { QuizQuestion } from './quizzes'

export const kvsCodingLessons: Lesson[] = [
  {
    id: "KVS-CT-A09-L03-PSEUDO-001",
    subject: "Coding",
    category: "Pseudocode",
    title: "Write Algorithms as Pseudocode",
    objectives: ["Represent simple sequence, selection and repetition ideas using consistent, language-independent pseudocode.", "வரிசை, நிபந்தனைத் தேர்வு மற்றும் மீட்சி கருத்துகளை ஒரே மாதிரியான, நிரல்மொழி சாராத படிநிலை குறியீட்டில் பிரதிநிதித்துவப்படுத்துதல்."],
    explanation: "Pseudocode communicates algorithmic logic without depending on one programming language. Indentation or consistent layout can show which steps belong inside a decision or loop. A trace tests what an algorithm would do for a specific input. Readable pseudocode should be unambiguous enough for another learner to trace. தமிழ்: வரிசை, நிபந்தனைத் தேர்வு மற்றும் மீட்சி கருத்துகளை ஒரே மாதிரியான, நிரல்மொழி சாராத படிநிலை குறியீட்டில் பிரதிநிதித்துவப்படுத்துதல்.",
    examples: ["INPUT age; IF age >= 10 THEN OUTPUT \"level 2\" ELSE OUTPUT \"level 1\".", "Translate a familiar step-by-step routine into INPUT/IF/OUTPUT style pseudocode."],
    summary: "Readable pseudocode should be unambiguous enough for another learner to trace.",
    difficulty: "intermediate",
    duration: 25,
    order: 101,
  },
  {
    id: "KVS-CT-A11-L03-DATATYPE-001",
    subject: "Coding",
    category: "Data Types",
    title: "Choose the Right Data Type",
    objectives: ["Distinguish common conceptual data types such as whole number, decimal number, text and Boolean, and choose suitable representations for simple problems.", "முழு எண், தசம எண், உரை, Boolean போன்ற அடிப்படை தரவு வகைகளை வேறுபடுத்தி எளிய பிரச்சினைகளுக்கு பொருத்தமான பிரதிநிதித்துவத்தைத் தேர்வு செய்தல்."],
    explanation: "A data type describes what kind of value a variable or field is intended to hold. Numbers used for calculation should not be stored as text unless there is a reason. Boolean values represent two logical states such as true/false. Choosing a suitable representation reduces ambiguity and supports correct operations. தமிழ்: முழு எண், தசம எண், உரை, Boolean போன்ற அடிப்படை தரவு வகைகளை வேறுபடுத்தி எளிய பிரச்சினைகளுக்கு பொருத்தமான பிரதிநிதித்துவத்தைத் தேர்வு செய்தல்.",
    examples: ["age=12 → whole number; temperature=18.5 → decimal number; name=\"Kavi\" → text; consentGiven=true → Boolean.", "Classify a small table of values by conceptual data type."],
    summary: "Choosing a suitable representation reduces ambiguity and supports correct operations.",
    difficulty: "intermediate",
    duration: 25,
    order: 102,
  },
  {
    id: "KVS-CT-A13-L03-BOOLEAN-001",
    subject: "Coding",
    category: "Boolean Logic",
    title: "Combine Conditions With Boolean Logic",
    objectives: ["Evaluate and construct compound conditions using AND, OR and NOT, and trace how they affect program decisions.", "AND, OR, NOT பயன்படுத்திய கூட்டு நிபந்தனைகளை மதிப்பீடு செய்து உருவாக்கி, அவை நிரல் முடிவுகளை எவ்வாறு பாதிக்கின்றன என்பதைப் பின்தொடர்தல்."],
    explanation: "A AND B is true only when both conditions are true. A OR B is true when at least one condition is true. NOT reverses a Boolean condition. Parentheses make the intended grouping of compound conditions explicit. தமிழ்: AND, OR, NOT பயன்படுத்திய கூட்டு நிபந்தனைகளை மதிப்பீடு செய்து உருவாக்கி, அவை நிரல் முடிவுகளை எவ்வாறு பாதிக்கின்றன என்பதைப் பின்தொடர்தல்.",
    examples: ["age>=13 AND permission=true requires both tests to pass.", "isWeekend OR isHoliday is true if either condition is true.", "Complete small truth tables for AND/OR/NOT."],
    summary: "Parentheses make the intended grouping of compound conditions explicit.",
    difficulty: "intermediate",
    duration: 25,
    order: 103,
  },
]

export const kvsCodingQuizzes: QuizQuestion[] = [
  {
    id: "KVS-Q-CT-A09-PSEUDO-00001",
    subject: "Coding",
    lessonId: "KVS-CT-A09-L03-PSEUDO-001",
    type: "mcq",
    question: "Which order best represents a simple input-process-output algorithm? — எளிய input-process-output அல்கோரிதத்திற்கான சரியான வரிசை எது?",
    options: ["INPUT value → calculate result → OUTPUT result", "OUTPUT result → INPUT value → calculate result", "calculate result → OUTPUT result → INPUT value"],
    correctAnswer: 0,
    explanation: "The algorithm must receive the value before using it and output after calculation. தமிழ்: முதலில் உள்ளீடு பெற வேண்டும்; பின்னர் கணக்கிட்டு வெளியீடு தர வேண்டும்.",
    difficulty: "medium",
  },
  {
    id: "KVS-Q-CT-A09-PSEUDO-00002",
    subject: "Coding",
    lessonId: "KVS-CT-A09-L03-PSEUDO-001",
    type: "mcq",
    question: "Pseudocode says IF score >= 10 THEN OUTPUT \"pass\" ELSE OUTPUT \"try again\". What happens for score=12? — score=12 என்றால் இந்த pseudocode என்ன வெளியிடும்?",
    options: ["pass", "try again", "nothing"],
    correctAnswer: 0,
    explanation: "12 satisfies score>=10. தமிழ்: 12 என்பது score>=10 நிபந்தனையை பூர்த்தி செய்கிறது.",
    difficulty: "medium",
  },
  {
    id: "KVS-Q-CT-A09-PSEUDO-00003",
    subject: "Coding",
    lessonId: "KVS-CT-A09-L03-PSEUDO-001",
    type: "short-answer",
    question: "Why can pseudocode be useful before choosing a programming language? — ஒரு நிரல்மொழியைத் தேர்வுசெய்யும் முன் pseudocode ஏன் பயனுள்ளதாக இருக்கும்?",
    correctAnswer: "It lets us plan and discuss the logic without being tied to one language’s syntax.",
    explanation: "Pseudocode separates algorithmic thinking from specific syntax. தமிழ்: Pseudocode குறிப்பிட்ட syntax-இலிருந்து தர்க்கத்தைப் பிரிக்க உதவுகிறது.",
    difficulty: "medium",
  },
  {
    id: "KVS-Q-CT-A09-PSEUDO-00004",
    subject: "Coding",
    lessonId: "KVS-CT-A09-L03-PSEUDO-001",
    type: "short-answer",
    question: "A learner writes steps that use a value before any INPUT or assignment gives it a value. What is the main problem? — ஒரு மதிப்புக்கு INPUT அல்லது assignment கொடுக்குமுன் அதைப் பயன்படுத்துகிறார். முக்கிய பிழை என்ன?",
    correctAnswer: "The algorithm tries to use data that has not been provided or defined.",
    explanation: "Trace the source of every value before it is used. தமிழ்: ஒவ்வொரு மதிப்பும் பயன்படுத்தப்படுமுன் அது எங்கிருந்து வருகிறது என்பதை உறுதி செய்ய வேண்டும்.",
    difficulty: "medium",
  },
  {
    id: "KVS-Q-CT-A11-DATATYPE-00001",
    subject: "Coding",
    lessonId: "KVS-CT-A11-L03-DATATYPE-001",
    type: "mcq",
    question: "Which conceptual data type best fits the value 27 when it represents a count of books? — 27 என்பது புத்தக எண்ணிக்கையை குறிக்கும்போது எந்த தரவு வகை பொருத்தமானது?",
    options: ["whole number", "text", "Boolean"],
    correctAnswer: 0,
    explanation: "A count with no fractional part is naturally represented as a whole number. தமிழ்: பகுதி இல்லாத எண்ணிக்கை முழு எண்ணாக பொருத்தமாகும்.",
    difficulty: "medium",
  },
  {
    id: "KVS-Q-CT-A11-DATATYPE-00002",
    subject: "Coding",
    lessonId: "KVS-CT-A11-L03-DATATYPE-001",
    type: "mcq",
    question: "Which type best fits a true/false setting such as notificationsEnabled? — notificationsEnabled போன்ற true/false அமைப்பிற்கு எந்த வகை பொருத்தமானது?",
    options: ["Boolean", "decimal", "text paragraph"],
    correctAnswer: 0,
    explanation: "A Boolean represents two logical states. தமிழ்: Boolean இரண்டு தர்க்க நிலைகளை பிரதிநிதித்துவப்படுத்துகிறது.",
    difficulty: "medium",
  },
  {
    id: "KVS-Q-CT-A11-DATATYPE-00003",
    subject: "Coding",
    lessonId: "KVS-CT-A11-L03-DATATYPE-001",
    type: "short-answer",
    question: "Why might a postcode such as “00120” be stored as text rather than a number for arithmetic? — “00120” போன்ற அஞ்சல் குறியீடு ஏன் கணக்கிடும் எண்ணாக அல்லாமல் உரையாக சேமிக்கப்படலாம்?",
    correctAnswer: "It is an identifier; leading zeroes can matter and arithmetic on it is usually meaningless.",
    explanation: "Representation should match how the value is used. தமிழ்: அது அடையாளம்; முன்னணி பூஜ்ஜியங்கள் முக்கியமாக இருக்கலாம்; கணிதச் செயல் பொருத்தமற்றது.",
    difficulty: "medium",
  },
  {
    id: "KVS-Q-CT-A11-DATATYPE-00004",
    subject: "Coding",
    lessonId: "KVS-CT-A11-L03-DATATYPE-001",
    type: "mcq",
    question: "A field stores temperature values such as 18.5 and 21.0 for calculations. Which representation is most suitable conceptually? — 18.5, 21.0 போன்ற வெப்பநிலைகளை கணக்கிட சேமிக்க எந்த பிரதிநிதித்துவம் பொருத்தமானது?",
    options: ["decimal number", "Boolean", "free text sentence"],
    correctAnswer: 0,
    explanation: "The data includes fractional numeric values used in calculations. தமிழ்: பகுதி கொண்ட எண் மதிப்புகள் கணக்கீட்டில் பயன்படுத்தப்படுகின்றன.",
    difficulty: "medium",
  },
  {
    id: "KVS-Q-CT-A13-BOOLEAN-00001",
    subject: "Coding",
    lessonId: "KVS-CT-A13-L03-BOOLEAN-001",
    type: "mcq",
    question: "For A=true and B=false, what is A AND B? — A=true, B=false என்றால் A AND B என்ன?",
    options: ["true", "false"],
    correctAnswer: 1,
    explanation: "AND is true only when both operands are true. தமிழ்: AND இரண்டும் true ஆனால்தான் true.",
    difficulty: "medium",
  },
  {
    id: "KVS-Q-CT-A13-BOOLEAN-00002",
    subject: "Coding",
    lessonId: "KVS-CT-A13-L03-BOOLEAN-001",
    type: "mcq",
    question: "For A=false and B=true, what is A OR B? — A=false, B=true என்றால் A OR B என்ன?",
    options: ["true", "false"],
    correctAnswer: 0,
    explanation: "OR is true when at least one operand is true. தமிழ்: OR-ல் குறைந்தது ஒன்று true என்றால் முடிவு true.",
    difficulty: "medium",
  },
  {
    id: "KVS-Q-CT-A13-BOOLEAN-00003",
    subject: "Coding",
    lessonId: "KVS-CT-A13-L03-BOOLEAN-001",
    type: "mcq",
    question: "A rule is age>=13 AND permission=true. A learner is 14 but permission=false. Does the rule pass? — age>=13 AND permission=true. வயது 14, permission=false. விதி நிறைவேறுமா?",
    options: ["Yes", "No"],
    correctAnswer: 1,
    explanation: "Both conditions are required by AND. தமிழ்: AND இரு நிபந்தனைகளையும் தேவைப்படுத்துகிறது.",
    difficulty: "medium",
  },
  {
    id: "KVS-Q-CT-A13-BOOLEAN-00004",
    subject: "Coding",
    lessonId: "KVS-CT-A13-L03-BOOLEAN-001",
    type: "short-answer",
    question: "Someone says A OR B means exactly one must be true. What is the correction for ordinary inclusive OR? — A OR B என்றால் ஒன்றே ஒன்று மட்டும் true ஆக வேண்டும் என்று கூறுகிறார். Inclusive OR-க்கு சரியான திருத்தம் என்ன?",
    correctAnswer: "Inclusive OR is true when at least one is true, including when both are true.",
    explanation: "Ordinary programming OR is generally inclusive unless a different operator is specified. தமிழ்: பொதுவான OR-ல் குறைந்தது ஒன்று true என்றால் போதும்; இரண்டும் true ஆனாலும் true.",
    difficulty: "medium",
  },
]
