import type { Lesson } from './lessons'
import type { QuizQuestion } from './quizzes'

export const kvsMathLessons: Lesson[] = [
  {
    id: "KVS-MATH-A09-L04-AREA-001",
    subject: "Mathematics",
    category: "Area",
    title: "Area: Measure the Space Inside",
    objectives: ["Calculate the area of rectangles and simple compound rectilinear shapes using square units and decomposition.", "சதுர அலகுகள் மற்றும் பகுத்தல் முறையைப் பயன்படுத்தி செவ்வகங்களும் எளிய கூட்டுவடிவங்களும் கொண்ட பரப்பளவை கணக்கிடுதல்."],
    explanation: "Area measures two-dimensional space inside a boundary. Rectangle area = length × width when lengths use compatible units. A compound rectilinear shape can be split into non-overlapping rectangles and the parts added. Area is measured in square units such as cm² and m². தமிழ்: சதுர அலகுகள் மற்றும் பகுத்தல் முறையைப் பயன்படுத்தி செவ்வகங்களும் எளிய கூட்டுவடிவங்களும் கொண்ட பரப்பளவை கணக்கிடுதல்.",
    examples: ["A 7 cm by 4 cm rectangle has area 28 cm².", "Split an L-shape into rectangles of 4×3 and 2×2: total area 12+4=16 square units.", "Count unit squares first, then connect rows × columns to multiplication."],
    summary: "Area is measured in square units such as cm² and m².",
    difficulty: "intermediate",
    duration: 25,
    order: 101,
  },
  {
    id: "KVS-MATH-A11-L05-ANGLES-001",
    subject: "Mathematics",
    category: "Angles",
    title: "Reason With Angles",
    objectives: ["Use angle facts on a straight line and around a point to find unknown angles and justify each step.", "நேர்கோட்டிலும் ஒரு புள்ளியைச் சுற்றியும் உள்ள கோண உண்மைகளைப் பயன்படுத்தி தெரியாத கோணங்களை கண்டறிந்து ஒவ்வொரு படியையும் விளக்குதல்."],
    explanation: "Angles on a straight line total 180°. Angles around a point total 360°. Reasoning should name the angle fact used, not only give an answer. Straight line: 180°. Around a point: 360°. தமிழ்: நேர்கோட்டிலும் ஒரு புள்ளியைச் சுற்றியும் உள்ள கோண உண்மைகளைப் பயன்படுத்தி தெரியாத கோணங்களை கண்டறிந்து ஒவ்வொரு படியையும் விளக்குதல்.",
    examples: ["If two adjacent angles on a straight line are 128° and x, x=52°.", "Around a point, 90°+110°+x=360°, so x=160°.", "Write the total first, subtract known angles, then state the fact."],
    summary: "Straight line: 180°. Around a point: 360°.",
    difficulty: "intermediate",
    duration: 25,
    order: 102,
  },
  {
    id: "KVS-MATH-A11-L06-VOLUME-001",
    subject: "Mathematics",
    category: "Volume",
    title: "Volume of Cuboids",
    objectives: ["Interpret volume as the number of unit cubes filling a three-dimensional space and calculate cuboid volume.", "முப்பரிமாண இடத்தை நிரப்பும் அலகுக் கனங்களின் எண்ணிக்கையாக கனஅளவைப் புரிந்து செவ்வக கனவடிவத்தின் கனஅளவை கணக்கிடுதல்."],
    explanation: "Volume measures three-dimensional space. Cuboid volume = length × width × height. Volume is measured in cubic units. A layer with length × width cubes repeated for the height gives the total volume. தமிழ்: முப்பரிமாண இடத்தை நிரப்பும் அலகுக் கனங்களின் எண்ணிக்கையாக கனஅளவைப் புரிந்து செவ்வக கனவடிவத்தின் கனஅளவை கணக்கிடுதல்.",
    examples: ["A 5 cm × 3 cm × 4 cm cuboid has volume 60 cm³.", "Build or sketch layers of unit cubes before using the formula."],
    summary: "A layer with length × width cubes repeated for the height gives the total volume.",
    difficulty: "intermediate",
    duration: 25,
    order: 103,
  },
]

export const kvsMathQuizzes: QuizQuestion[] = [
  {
    id: "KVS-Q-MATH-A09-AREA-00001",
    subject: "Mathematics",
    lessonId: "KVS-MATH-A09-L04-AREA-001",
    type: "mcq",
    question: "A rectangle is 8 cm long and 5 cm wide. What is its area? — ஒரு செவ்வகம் 8 செ.மீ நீளமும் 5 செ.மீ அகலமும் கொண்டது. அதன் பரப்பளவு என்ன?",
    options: ["13 cm²", "40 cm²", "26 cm²"],
    correctAnswer: 1,
    explanation: "Area = 8 × 5 = 40 cm². தமிழ்: பரப்பளவு = 8 × 5 = 40 செ.மீ².",
    difficulty: "medium",
  },
  {
    id: "KVS-Q-MATH-A09-AREA-00002",
    subject: "Mathematics",
    lessonId: "KVS-MATH-A09-L04-AREA-001",
    type: "short-answer",
    question: "Why is the unit for area written as cm² rather than cm? — பரப்பளவின் அலகு ஏன் செ.மீ என்பதற்குப் பதில் செ.மீ² என எழுதப்படுகிறது?",
    correctAnswer: "Because area counts two-dimensional square units.",
    explanation: "Area covers two dimensions, so it is measured in square units. தமிழ்: பரப்பளவு இரு பரிமாணங்களைக் கொண்டதால் சதுர அலகுகளில் அளவிடப்படுகிறது.",
    difficulty: "medium",
  },
  {
    id: "KVS-Q-MATH-A09-AREA-00003",
    subject: "Mathematics",
    lessonId: "KVS-MATH-A09-L04-AREA-001",
    type: "mcq",
    question: "An L-shape is split into two non-overlapping rectangles with areas 18 cm² and 12 cm². What is the total area? — ஒரு L வடிவு ஒன்றுடன் ஒன்று மேலிடாத இரண்டு செவ்வகங்களாகப் பிரிக்கப்பட்டுள்ளது; அவற்றின் பரப்பளவுகள் 18 செ.மீ² மற்றும் 12 செ.மீ². மொத்த பரப்பளவு என்ன?",
    options: ["6 cm²", "30 cm²", "216 cm²"],
    correctAnswer: 1,
    explanation: "Add the non-overlapping parts: 18+12=30. தமிழ்: மேலிடாத பகுதிகளின் பரப்பளவுகளை கூட்ட வேண்டும்: 18+12=30.",
    difficulty: "medium",
  },
  {
    id: "KVS-Q-MATH-A09-AREA-00004",
    subject: "Mathematics",
    lessonId: "KVS-MATH-A09-L04-AREA-001",
    type: "short-answer",
    question: "A learner says a 6 cm by 4 cm rectangle has area 20 cm² because 6+4+6+4=20. What did they calculate? — 6 செ.மீ × 4 செ.மீ செவ்வகத்தின் பரப்பளவு 20 செ.மீ² என்று ஒரு மாணவர் கூறுகிறார்; ஏனெனில் 6+4+6+4=20. அவர் உண்மையில் எதை கணக்கிட்டார்?",
    correctAnswer: "They calculated the perimeter, not the area.",
    explanation: "Adding all side lengths gives perimeter; area is 6×4=24 cm². தமிழ்: அனைத்து பக்க நீளங்களையும் கூட்டுவது சுற்றளவு; பரப்பளவு 6×4=24 செ.மீ².",
    difficulty: "medium",
  },
  {
    id: "KVS-Q-MATH-A11-ANGLES-00001",
    subject: "Mathematics",
    lessonId: "KVS-MATH-A11-L05-ANGLES-001",
    type: "mcq",
    question: "Two adjacent angles form a straight line. One is 137°. What is the other? — ஒரு நேர்கோட்டில் உள்ள அடுத்தடுத்த இரண்டு கோணங்களில் ஒன்று 137°. மற்ற கோணம் எவ்வளவு?",
    options: ["43°", "137°", "223°"],
    correctAnswer: 0,
    explanation: "Angles on a straight line total 180°, so 180−137=43. தமிழ்: நேர்கோட்டிலுள்ள கோணங்கள் 180°; ஆகவே 180−137=43°.",
    difficulty: "medium",
  },
  {
    id: "KVS-Q-MATH-A11-ANGLES-00002",
    subject: "Mathematics",
    lessonId: "KVS-MATH-A11-L05-ANGLES-001",
    type: "mcq",
    question: "Angles around a point are 95°, 105° and x. Find x. — ஒரு புள்ளியைச் சுற்றிய கோணங்கள் 95°, 105° மற்றும் x. x-ஐ கண்டறிக.",
    options: ["160°", "180°", "200°"],
    correctAnswer: 0,
    explanation: "Around a point totals 360°; x=360−200=160. தமிழ்: ஒரு புள்ளியைச் சுற்றிய கோணங்களின் மொத்தம் 360°; x=160°.",
    difficulty: "medium",
  },
  {
    id: "KVS-Q-MATH-A11-ANGLES-00003",
    subject: "Mathematics",
    lessonId: "KVS-MATH-A11-L05-ANGLES-001",
    type: "short-answer",
    question: "A diagram looks as if an angle is 90°, but no right-angle marker or measurement is given. What should you do? — ஒரு வரைபடத்தில் கோணம் 90° போலத் தெரிகிறது; ஆனால் குறியீடும் அளவும் தரப்படவில்லை. என்ன செய்ய வேண்டும்?",
    correctAnswer: "Use only the stated angle facts and given information, not the appearance of the diagram.",
    explanation: "Geometry diagrams may not be to scale; justify using known facts. தமிழ்: வடிவியல் வரைபடம் அளவுத்தொகைக்கு ஏற்றதாக இருக்க வேண்டியதில்லை; கொடுக்கப்பட்ட உண்மைகளால் நிரூபிக்க வேண்டும்.",
    difficulty: "medium",
  },
  {
    id: "KVS-Q-MATH-A11-ANGLES-00004",
    subject: "Mathematics",
    lessonId: "KVS-MATH-A11-L05-ANGLES-001",
    type: "short-answer",
    question: "Three angles around a point are 120°, 80° and 70°. A fourth angle is missing. Find it and name the fact used. — ஒரு புள்ளியைச் சுற்றி 120°, 80°, 70° என்ற மூன்று கோணங்கள் உள்ளன. நான்காவது கோணத்தை கண்டறிந்து பயன்படுத்திய உண்மையைச் சொல்லுக.",
    correctAnswer: "90°, because angles around a point total 360°.",
    explanation: "120+80+70=270; 360−270=90. தமிழ்: 120+80+70=270; 360−270=90°.",
    difficulty: "medium",
  },
  {
    id: "KVS-Q-MATH-A11-VOLUME-00001",
    subject: "Mathematics",
    lessonId: "KVS-MATH-A11-L06-VOLUME-001",
    type: "mcq",
    question: "Find the volume of a cuboid 6 cm × 4 cm × 3 cm. — 6 செ.மீ × 4 செ.மீ × 3 செ.மீ அளவுள்ள செவ்வக கனவடிவத்தின் கனஅளவை கண்டறிக.",
    options: ["13 cm³", "72 cm³", "24 cm³"],
    correctAnswer: 1,
    explanation: "6×4×3=72 cm³. தமிழ்: 6×4×3=72 செ.மீ³.",
    difficulty: "medium",
  },
  {
    id: "KVS-Q-MATH-A11-VOLUME-00002",
    subject: "Mathematics",
    lessonId: "KVS-MATH-A11-L06-VOLUME-001",
    type: "short-answer",
    question: "Why is cuboid volume measured in cubic units? — செவ்வக கனவடிவத்தின் கனஅளவு ஏன் கன அலகுகளில் அளவிடப்படுகிறது?",
    correctAnswer: "Because volume counts three-dimensional unit cubes filling space.",
    explanation: "Volume has three dimensions and can be modelled by unit cubes. தமிழ்: கனஅளவு மூன்று பரிமாணங்களைக் கொண்டது; அலகுக் கனங்களால் மாதிரிபடுத்தலாம்.",
    difficulty: "medium",
  },
  {
    id: "KVS-Q-MATH-A11-VOLUME-00003",
    subject: "Mathematics",
    lessonId: "KVS-MATH-A11-L06-VOLUME-001",
    type: "mcq",
    question: "A cuboid has volume 120 cm³, length 10 cm and width 4 cm. What is its height? — ஒரு செவ்வக கனவடிவத்தின் கனஅளவு 120 செ.மீ³, நீளம் 10 செ.மீ, அகலம் 4 செ.மீ. உயரம் எவ்வளவு?",
    options: ["3 cm", "30 cm", "6 cm"],
    correctAnswer: 0,
    explanation: "10×4×h=120, so h=120÷40=3. தமிழ்: 10×4×h=120; ஆகவே h=3 செ.மீ.",
    difficulty: "medium",
  },
  {
    id: "KVS-Q-MATH-A11-VOLUME-00004",
    subject: "Mathematics",
    lessonId: "KVS-MATH-A11-L06-VOLUME-001",
    type: "short-answer",
    question: "A learner adds 5+3+2 and says a 5×3×2 cuboid has volume 10 cm³. What is the correction? — 5×3×2 செவ்வக கனவடிவத்தின் கனஅளவு 10 செ.மீ³ என்று 5+3+2 கூட்டி ஒரு மாணவர் கூறுகிறார். சரியான திருத்தம் என்ன?",
    correctAnswer: "Multiply the three dimensions: 5×3×2=30 cm³.",
    explanation: "Volume of a cuboid is length×width×height, not the sum. தமிழ்: கனஅளவு = நீளம்×அகலம்×உயரம்; கூட்டல் அல்ல.",
    difficulty: "medium",
  },
]
