import type { Lesson } from './lessons'
import type { QuizQuestion } from './quizzes'

const lesson = (v: [string,string,string,string,string,string,string,string[],string,number,number]): Lesson => ({
  id:v[0], subject:v[1], category:v[2], title:v[3], objectives:[v[4],v[5]], explanation:v[6], examples:v[7], summary:v[8], difficulty:'beginner', duration:v[9], order:v[10],
})
const mcq = (v: [string,string,string,string,string[],number,string]): QuizQuestion => ({
  id:v[0], subject:v[1], lessonId:v[2], type:'mcq', question:v[3], options:v[4], correctAnswer:v[5], explanation:v[6], difficulty:'easy',
})
const short = (v: [string,string,string,string,string,string]): QuizQuestion => ({
  id:v[0], subject:v[1], lessonId:v[2], type:'short-answer', question:v[3], correctAnswer:v[4], explanation:v[5], difficulty:'easy',
})

export const kvsFoundationLessons: Lesson[] = [
  lesson(["KVS-MATH-A03-L03-SHAPE-001","Mathematics","2D Shape","Meet Circles, Triangles, Squares and Rectangles / வட்டம், முக்கோணம், சதுரம், செவ்வகம் அறிமுகம்","Recognise common 2D shapes by visible properties such as straight/curved edges and corners, without relying only on orientation or colour.","நிறம் அல்லது திருப்பிய நிலையை மட்டும் சாராமல், நேரான/வளைந்த ஓரங்கள் மற்றும் மூலைகள் போன்ற கண்ணுக்கு தெரியும் பண்புகளால் பொதுவான 2D வடிவங்களை அடையாளம் காணுதல்.","A circle has one continuous curved boundary and no corners. A triangle has three straight sides and three corners. A square has four equal straight sides; a rectangle has four straight sides and four corners. தமிழ் நோக்கம்: நிறம் அல்லது திருப்பிய நிலையை மட்டும் சாராமல், நேரான/வளைந்த ஓரங்கள் மற்றும் மூலைகள் போன்ற கண்ணுக்கு தெரியும் பண்புகளால் பொதுவான 2D வடிவங்களை அடையாளம் காணுதல்.",["Turn a triangle picture sideways and show that it is still a triangle.","Sort shape cards by number of corners."],"A circle has one continuous curved boundary and no corners. A triangle has three straight sides and three corners.",15,301]),
  lesson(["KVS-SCI-A03-L02-OBSERVE-001","Science","Observation and Sorting","Look Closely: Observe and Sort / கவனமாகப் பார்ப்போம்: கவனித்து வகைப்படுத்துவோம்","Use safe senses such as sight and touch to describe visible/tactile properties and sort classroom objects by one stated rule.","பார்வை மற்றும் பாதுகாப்பான தொடுதல் போன்ற உணர்வுகளைப் பயன்படுத்தி கண்ணுக்கு தெரியும்/தொட்டுணரும் பண்புகளை விவரித்து, கூறப்பட்ட ஒரு விதியின்படி வகுப்பறை பொருட்களை வகைப்படுத்துதல்.","An observation describes what is noticed directly. A sorting rule should be stated clearly, such as “smooth/rough” or “red/not red.” Objects can be sorted differently when the rule changes. தமிழ் நோக்கம்: பார்வை மற்றும் பாதுகாப்பான தொடுதல் போன்ற உணர்வுகளைப் பயன்படுத்தி கண்ணுக்கு தெரியும்/தொட்டுணரும் பண்புகளை விவரித்து, கூறப்பட்ட ஒரு விதியின்படி வகுப்பறை பொருட்களை வகைப்படுத்துதல்.",["Sort two safe objects by texture, then sort the same objects by colour.","Say one observation before making a guess."],"An observation describes what is noticed directly. A sorting rule should be stated clearly, such as “smooth/rough” or “red/not red.”",15,302]),
  lesson(["KVS-TAM-A03-L03-MEI-001","Tamil","மெய்யெழுத்துகள்","மெய்யெழுத்துகளை அறிந்துகொள்வோம்","Recognise selected Tamil consonant letters as மெய்யெழுத்துகள் and distinguish them from familiar உயிரெழுத்துகள்.","தேர்ந்தெடுக்கப்பட்ட தமிழ் மெய்யெழுத்துகளை அடையாளம் கண்டு, ஏற்கனவே அறிந்த உயிரெழுத்துகளிலிருந்து வேறுபடுத்துதல்.","தமிழில் மெய்யெழுத்துகள் புள்ளியுடன் எழுதப்படும் அடிப்படை மெய் வடிவங்களை உடையவை. க், ங், ச் போன்றவை மெய்யெழுத்துகளின் எடுத்துக்காட்டுகள். உயிரெழுத்தும் மெய்யெழுத்தும் சேர்ந்து உயிர்மெய்யெழுத்து உருவாகும். தமிழ் நோக்கம்: தேர்ந்தெடுக்கப்பட்ட தமிழ் மெய்யெழுத்துகளை அடையாளம் கண்டு, ஏற்கனவே அறிந்த உயிரெழுத்துகளிலிருந்து வேறுபடுத்துதல்.",["க் மற்றும் க ஆகியவற்றை ஒப்பிட்டு புள்ளியின் பங்கை கவனிக்கவும்.","க், ச், த் ஆகியவற்றை அ, இ, உ என்பவற்றிலிருந்து பிரிக்கவும்."],"தமிழில் மெய்யெழுத்துகள் புள்ளியுடன் எழுதப்படும் அடிப்படை மெய் வடிவங்களை உடையவை. க், ங், ச் போன்றவை மெய்யெழுத்துகளின் எடுத்துக்காட்டுகள்.",15,303]),
  lesson(["KVS-ENG-A03-L02-RHYME-001","English","Rhythm and Rhyme","Hear Rhymes and Word Beats / ஒத்த ஒலியும் சொல்லின் தாள்தட்டுகளும் கேட்போம்","Notice simple rhyming word endings and clap syllable beats in familiar spoken words without requiring formal spelling knowledge.","எழுத்துப்பிழையில்லா எழுத்தறிவை வேண்டாமல், பரிச்சயமான ஆங்கிலச் சொற்களில் ஒத்த முடிவு ஒலிகளையும் அசைத் தாள்களையும் கேட்டு அடையாளம் காணுதல்.","Rhyming words share the same or similar ending sound, such as cat/hat. A spoken word can be broken into syllable beats, such as ap-ple (two beats). Rhyme is about sound, not simply matching written letters. தமிழ் நோக்கம்: எழுத்துப்பிழையில்லா எழுத்தறிவை வேண்டாமல், பரிச்சயமான ஆங்கிலச் சொற்களில் ஒத்த முடிவு ஒலிகளையும் அசைத் தாள்களையும் கேட்டு அடையாளம் காணுதல்.",["Say “cat, hat, sun” and listen for the two that rhyme.","Clap the beats in “ti-ger” and “cat.”"],"Rhyming words share the same or similar ending sound, such as cat/hat. A spoken word can be broken into syllable beats, such as ap-ple (two beats).",15,304]),
  lesson(["KVS-MATH-A05-L04-BONDS-001","Mathematics","Number Bonds","Find Number Bonds to 10 / 10 ஆகும் எண் ஜோடிகளை கண்டுபிடிப்போம்","Recall and represent pairs of whole numbers that total 10, using objects, drawings and equations.","பொருட்கள், படங்கள், சமன்பாடுகள் மூலம் மொத்தம் 10 ஆகும் முழு எண் ஜோடிகளை நினைவுகூர்ந்து பிரதிநிதித்துவப்படுத்துதல்.","A number bond shows parts that combine to make a whole. If 6 + 4 = 10, then 4 + 6 = 10. Knowing bonds to 10 supports mental addition and subtraction. தமிழ் நோக்கம்: பொருட்கள், படங்கள், சமன்பாடுகள் மூலம் மொத்தம் 10 ஆகும் முழு எண் ஜோடிகளை நினைவுகூர்ந்து பிரதிநிதித்துவப்படுத்துதல்.",["Use ten counters: hide 3; 7 remain visible, so 3 + 7 = 10.","Complete 8 + __ = 10 with counters."],"A number bond shows parts that combine to make a whole. If 6 + 4 = 10, then 4 + 6 = 10.",20,305]),
  lesson(["KVS-CT-A05-L02-IO-001","Coding","Input and Output","What Goes In? What Comes Out? / எது உள்ளே செல்கிறது? எது வெளியே வருகிறது?","Classify simple examples of information/actions as inputs or outputs in familiar digital and non-digital systems.","பரிச்சயமான டிஜிட்டல் மற்றும் டிஜிட்டல் அல்லாத அமைப்புகளில் தகவல்/செயலை உள்ளீடு அல்லது வெளியீடாக வகைப்படுத்துதல்.","An input provides information or an action to a system. An output is a result produced by a system. The same physical device can sometimes support different roles, so describe the specific action. தமிழ் நோக்கம்: பரிச்சயமான டிஜிட்டல் மற்றும் டிஜிட்டல் அல்லாத அமைப்புகளில் தகவல்/செயலை உள்ளீடு அல்லது வெளியீடாக வகைப்படுத்துதல்.",["Pressing a keyboard key is an input action; a character appearing on the screen is an output.","Sort picture cards into input/output examples."],"An input provides information or an action to a system. An output is a result produced by a system.",20,306]),
]

export const kvsFoundationQuizzes: QuizQuestion[] = [
  mcq(["KVS-Q-MATH-A03-SHAPE-00001","Mathematics","KVS-MATH-A03-L03-SHAPE-001","Which shape has three straight sides? — மூன்று நேரான பக்கங்கள் கொண்ட வடிவம் எது?",["Triangle","Circle","Square"],0,"A triangle has three straight sides. தமிழ்: முக்கோணத்திற்கு மூன்று நேரான பக்கங்கள் உள்ளன."]),
  mcq(["KVS-Q-MATH-A03-SHAPE-00002","Mathematics","KVS-MATH-A03-L03-SHAPE-001","A triangle card is turned upside down. What shape is it now? — முக்கோண அட்டை தலைகீழாக திருப்பப்பட்டது. இப்போது அது என்ன வடிவம்?",["Triangle","Circle","It has no shape"],0,"Turning a shape does not change its defining sides and corners. தமிழ்: வடிவத்தைத் திருப்பினாலும் அதன் பக்கங்களும் மூலைகளும் மாறாது."]),
  short(["KVS-Q-MATH-A03-SHAPE-00003","Mathematics","KVS-MATH-A03-L03-SHAPE-001","Match: circle, triangle, square to 0, 3, 4 corners. — பொருத்துக: வட்டம், முக்கோணம், சதுரம் — 0, 3, 4 மூலைகள்.","circle → 0; triangle → 3; square → 4","Counting corners is one way to distinguish these shapes. தமிழ்: மூலைகளை எண்ணுவது இவ்வடிவங்களை வேறுபடுத்த உதவும்."]),
  short(["KVS-Q-MATH-A03-SHAPE-00004","Mathematics","KVS-MATH-A03-L03-SHAPE-001","A red square and a blue square have different colours. Are they still the same kind of shape? Why? — சிவப்பு சதுரமும் நீல சதுரமும் வேறு நிறம். அவை இன்னும் ஒரே வகை வடிவமா? ஏன்?","Yes. Colour does not change the square’s shape properties.","Shape is determined by geometric properties, not colour. தமிழ்: வடிவம் நிறத்தால் அல்ல, அதன் வடிவியல் பண்புகளால் தீர்மானிக்கப்படுகிறது."]),
  mcq(["KVS-Q-SCI-A03-OBSERVE-00001","Science","KVS-SCI-A03-L02-OBSERVE-001","Which sentence is a direct observation? — நேரடி கவனிப்பு எது?",["The block is red.","The block is lucky.","The block wants to move."],0,"“Red” describes a visible property. தமிழ்: “சிவப்பு” என்பது கண்ணுக்கு தெரியும் பண்பு."]),
  mcq(["KVS-Q-SCI-A03-OBSERVE-00002","Science","KVS-SCI-A03-L02-OBSERVE-001","You first sort buttons by colour, then by size. Is the second sort automatically wrong? — முதலில் பொத்தான்களை நிறப்படி, பின்னர் அளவுப்படி வகைப்படுத்துகிறீர்கள். இரண்டாவது வகைப்படுத்தல் தானாகவே தவறா?",["No. Different clear rules can produce different valid groups.","Yes, there can be only one rule."],0,"The sorting rule determines the grouping. தமிழ்: வகைப்படுத்தும் விதியே குழுவை நிர்ணயிக்கிறது."]),
  short(["KVS-Q-SCI-A03-OBSERVE-00003","Science","KVS-SCI-A03-L02-OBSERVE-001","“I do not need to say my sorting rule; everyone will know it.” What is the problem? — “என் வகைப்படுத்தும் விதியைச் சொல்லத் தேவையில்லை; அனைவருக்கும் தெரியும்” என்ற கூற்றில் பிரச்சினை என்ன?","Without the rule, others cannot check or repeat the sorting consistently.","A clear rule makes the classification understandable and repeatable. தமிழ்: தெளிவான விதி வகைப்படுத்தலை புரிந்து மீண்டும் செய்ய உதவும்."]),
  mcq(["KVS-Q-SCI-A03-OBSERVE-00004","Science","KVS-SCI-A03-L02-OBSERVE-001","Which is the safest way to investigate an unknown classroom material? — அறியாத வகுப்பறை பொருளை ஆராய்வதற்கான பாதுகாப்பான வழி எது?",["Follow adult instructions and observe without tasting or smelling it.","Taste it to identify it.","Put it near your eyes."],0,"Unknown materials should not be tasted or deliberately smelled. தமிழ்: அறியாத பொருட்களை ருசிக்கவோ திட்டமிட்டு மணக்கவோ கூடாது."]),
  mcq(["KVS-Q-TAM-A03-MEI-00001","Tamil","KVS-TAM-A03-L03-MEI-001","Which is a Tamil மெய்யெழுத்து? — கீழே எது மெய்யெழுத்து?",["க்","அ","இ"],0,"க் என்பது புள்ளியுடன் எழுதப்படும் மெய்யெழுத்து வடிவம். தமிழ்: க் என்பது மெய்யெழுத்து."]),
  short(["KVS-Q-TAM-A03-MEI-00002","Tamil","KVS-TAM-A03-L03-MEI-001","Match the letters to the groups உயிரெழுத்து / மெய்யெழுத்து: அ, க். — அ, க் ஆகியவற்றை உயிரெழுத்து / மெய்யெழுத்து குழுக்களுடன் பொருத்துக.","அ → உயிரெழுத்து; க் → மெய்யெழுத்து","அ உயிரெழுத்து; க் மெய்யெழுத்து. தமிழ்: அ உயிரெழுத்து; க் மெய்யெழுத்து."]),
  short(["KVS-Q-TAM-A03-MEI-00003","Tamil","KVS-TAM-A03-L03-MEI-001","“க் மற்றும் க ஒரே எழுத்து வடிவம்; புள்ளிக்கு பொருள் இல்லை” என்ற கூற்றில் பிழை என்ன? — “க் மற்றும் க ஒரே எழுத்து வடிவம்; புள்ளிக்கு பொருள் இல்லை” என்ற கூற்றில் பிழை என்ன?","புள்ளி மெய் வடிவத்தை குறிக்க உதவுகிறது; க் மற்றும் க ஒரே எழுத்து வடிவமல்ல.","தமிழ் எழுத்து அமைப்பில் புள்ளி முக்கிய வேறுபாட்டை உருவாக்குகிறது. தமிழ்: தமிழ் எழுத்து அமைப்பில் புள்ளி முக்கிய வேறுபாட்டை உருவாக்குகிறது."]),
  short(["KVS-Q-TAM-A03-MEI-00004","Tamil","KVS-TAM-A03-L03-MEI-001","அ மற்றும் க் ஆகியவற்றில் எது தனியாக உயிரெழுத்து? எப்படி தெரியும்? — அ மற்றும் க் ஆகியவற்றில் எது தனியாக உயிரெழுத்து? எப்படி தெரியும்?","அ. அது உயிரெழுத்து; க் மெய்யெழுத்து.","அ உயிரெழுத்துகளின் குழுவைச் சேர்ந்தது; க் மெய்யெழுத்து. தமிழ்: அ உயிரெழுத்து; க் மெய்யெழுத்து என்பதால் குழுவை அறியலாம்."]),
  mcq(["KVS-Q-ENG-A03-RHYME-00001","English","KVS-ENG-A03-L02-RHYME-001","Which word rhymes with “cat”? — “cat” என்ற சொல்லுடன் ஒத்த ஒலி தருவது எது?",["hat","sun","dog"],0,"Cat and hat share the ending sound /at/. தமிழ்: cat மற்றும் hat ஆகியவற்றின் முடிவு ஒலி ஒரேபோல் உள்ளது."]),
  mcq(["KVS-Q-ENG-A03-RHYME-00002","English","KVS-ENG-A03-L02-RHYME-001","You clap “ap-ple” as ap | ple. How many spoken beats are you showing? — “ap-ple” என்பதை ap | ple எனத் தட்டுகிறீர்கள். எத்தனை ஒலி அசைகளை காட்டுகிறீர்கள்?",["1","2","3"],1,"The word is being spoken in two syllable beats. தமிழ்: அந்த சொல் இரண்டு அசைத் தாள்களாக சொல்லப்படுகிறது."]),
  short(["KVS-Q-ENG-A03-RHYME-00003","English","KVS-ENG-A03-L02-RHYME-001","“Ball and bell rhyme because they start with the same letter.” What is wrong with the rule? — “ball மற்றும் bell ஒரே எழுத்தில் தொடங்குவதால் அவை rhyme” என்ற விதியில் பிழை என்ன?","Rhyme depends mainly on the ending sound, not the first letter.","Words can start the same without rhyming. தமிழ்: ஒரே தொடக்க எழுத்து இருந்தாலும் சொற்கள் ஒத்த முடிவு ஒலி தராமல் இருக்கலாம்."]),
  short(["KVS-Q-ENG-A03-RHYME-00004","English","KVS-ENG-A03-L02-RHYME-001","Why can rhyme practice be done before a child can spell every word? — குழந்தை எல்லா சொற்களையும் எழுத்துக்கூட்டத் தெரியுமுன் rhyme பயிற்சி ஏன் செய்யலாம்?","Rhyme can be heard in spoken sounds, so spelling is not required to notice it.","Phonological awareness begins with listening to speech sounds. தமிழ்: ஒலி விழிப்புணர்வு பேசும் ஒலிகளை கேட்பதிலிருந்து தொடங்கலாம்."]),
  mcq(["KVS-Q-MATH-A05-BONDS-00001","Mathematics","KVS-MATH-A05-L04-BONDS-001","What number completes 7 + __ = 10? — 7 + __ = 10 இல் விடுபட்ட எண் எது?",["2","3","4"],1,"7 and 3 are parts that make the whole 10. தமிழ்: 7 மற்றும் 3 சேர்ந்து 10 ஆகும்."]),
  mcq(["KVS-Q-MATH-A05-BONDS-00002","Mathematics","KVS-MATH-A05-L04-BONDS-001","Which pair makes 10? — எந்த ஜோடி 10 ஆகும்?",["6 and 4","6 and 3","5 and 4"],0,"6 + 4 = 10. தமிழ்: 6 + 4 = 10."]),
  short(["KVS-Q-MATH-A05-BONDS-00003","Mathematics","KVS-MATH-A05-L04-BONDS-001","“Because 2 + 8 = 10, 8 + 2 cannot also equal 10.” What is the error? — “2 + 8 = 10 என்பதால் 8 + 2 = 10 ஆகாது” என்ற கூற்றில் பிழை என்ன?","The order of addends can change without changing the total.","Both 2 + 8 and 8 + 2 equal 10. தமிழ்: 2 + 8 மற்றும் 8 + 2 இரண்டும் 10."]),
  short(["KVS-Q-MATH-A05-BONDS-00004","Mathematics","KVS-MATH-A05-L04-BONDS-001","How can knowing 9 + 1 = 10 help with 10 − 9? — 9 + 1 = 10 என்பதை அறிந்தால் 10 − 9 ஐ எவ்வாறு உதவுகிறது?","It shows the missing part is 1, so 10 − 9 = 1.","Addition and subtraction can describe the same part-whole relationship. தமிழ்: கூட்டலும் கழித்தலும் ஒரே பகுதி-முழு உறவை விவரிக்கலாம்."]),
  mcq(["KVS-Q-CT-A05-IO-00001","Coding","KVS-CT-A05-L02-IO-001","You press a key and a letter appears on the screen. What is the key press? — ஒரு விசையை அழுத்த, திரையில் எழுத்து தோன்றுகிறது. விசை அழுத்துதல் என்ன?",["Input","Output","Neither"],0,"The key press sends an action into the system. தமிழ்: விசை அழுத்துதல் அமைப்பிற்கு ஒரு செயலை உள்ளீடாக அனுப்புகிறது."]),
  mcq(["KVS-Q-CT-A05-IO-00002","Coding","KVS-CT-A05-L02-IO-001","In the same example, what is the letter appearing on the screen? — அதே எடுத்துக்காட்டில் திரையில் தோன்றும் எழுத்து என்ன?",["Output","Input","A password"],0,"The displayed letter is a result produced by the system. தமிழ்: திரையில் தோன்றும் எழுத்து அமைப்பு உருவாக்கும் வெளியீடு."]),
  short(["KVS-Q-CT-A05-IO-00003","Coding","KVS-CT-A05-L02-IO-001","“Anything that happens first is an input and anything later is an output.” Why is this rule weak? — “முதலில் நடப்பது உள்ளீடு; பின்னர் நடப்பது வெளியீடு” என்ற விதி ஏன் போதாது?","Input/output describe roles in relation to a system, not just time order.","The role depends on what crosses into or out of the chosen system. தமிழ்: உள்ளீடு/வெளியீடு என்பது நேர வரிசை மட்டும் அல்ல; அமைப்புடன் உள்ள உறவைச் சொல்கிறது."]),
  mcq(["KVS-Q-CT-A05-IO-00004","Coding","KVS-CT-A05-L02-IO-001","A calculator receives the numbers 2 and 3 and displays 5. Which is the output? — கணிப்பான் 2 மற்றும் 3 ஐப் பெற்று 5 ஐக் காட்டுகிறது. வெளியீடு எது?",["The displayed 5","The number 2 only","The button press only"],0,"The result shown by the system is the output. தமிழ்: அமைப்பு காட்டும் முடிவு 5 வெளியீடு."]),
]
