export interface Lesson {
  id: string;
  subject: string;
  category: string;
  title: string;
  objectives: string[];
  explanation: string;
  examples: string[];
  summary: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  duration: number; // minutes
  order: number;
}

export const lessons: Lesson[] = [
  // MATHEMATICS (15 lessons)
  {
    id: 'math-001',
    subject: 'Mathematics',
    category: 'Numbers',
    title: 'Understanding Place Value',
    objectives: ['Understand the place value system', 'Identify ones, tens, hundreds places', 'Expand numbers using place value'],
    explanation: 'Place value is the value of a digit based on its position in a number. In the number 345, the 3 is in the hundreds place (300), the 4 is in the tens place (40), and the 5 is in the ones place (5).',
    examples: ['456 = 400 + 50 + 6', '789 = 700 + 80 + 9', '203 = 200 + 0 + 3'],
    summary: 'Every digit in a number has a place value. The position determines whether it represents ones, tens, hundreds, or thousands.',
    difficulty: 'beginner',
    duration: 10,
    order: 1,
  },
  {
    id: 'math-002',
    subject: 'Mathematics',
    category: 'Numbers',
    title: 'Addition with Regrouping',
    objectives: ['Add two-digit numbers with regrouping', 'Understand carrying in addition', 'Solve word problems involving addition'],
    explanation: 'When adding numbers, if the sum of digits in one place is 10 or more, we regroup (carry) to the next place. For example, 27 + 15: add the ones (7+5=12), write 2 and carry 1, then add tens (2+1+1=4).',
    examples: ['27 + 15 = 42', '38 + 24 = 62', '45 + 37 = 82'],
    summary: 'Regrouping (carrying) allows us to add numbers that create sums of 10 or more in any place value.',
    difficulty: 'beginner',
    duration: 12,
    order: 2,
  },
  {
    id: 'math-003',
    subject: 'Mathematics',
    category: 'Numbers',
    title: 'Subtraction with Regrouping',
    objectives: ['Subtract two-digit numbers with regrouping', 'Understand borrowing in subtraction', 'Check subtraction using addition'],
    explanation: 'When subtracting, if the digit in the ones place of the top number is smaller than the digit below it, we borrow from the tens place. For example, 42 - 15: cannot do 2-5, so borrow 1 ten (making it 12-5=7), then 3-1=2.',
    examples: ['42 - 15 = 27', '50 - 23 = 27', '61 - 18 = 43'],
    summary: 'Borrowing (regrouping) in subtraction allows us to subtract when the top digit is smaller.',
    difficulty: 'beginner',
    duration: 12,
    order: 3,
  },
  {
    id: 'math-004',
    subject: 'Mathematics',
    category: 'Multiplication',
    title: 'Introduction to Multiplication',
    objectives: ['Understand multiplication as repeated addition', 'Learn multiplication facts 1-5', 'Solve simple multiplication problems'],
    explanation: 'Multiplication is a faster way to add equal groups. 3 × 4 means 3 groups of 4, which equals 4 + 4 + 4 = 12. The first number tells us how many groups, the second tells us how many in each group.',
    examples: ['2 × 3 = 6 (two groups of three)', '3 × 4 = 12 (three groups of four)', '4 × 5 = 20 (four groups of five)'],
    summary: 'Multiplication is repeated addition. It helps us count equal groups quickly.',
    difficulty: 'beginner',
    duration: 15,
    order: 4,
  },
  {
    id: 'math-005',
    subject: 'Mathematics',
    category: 'Multiplication',
    title: 'Multiplication Facts 6-10',
    objectives: ['Master multiplication facts 6-10', 'Use multiplication in real-world contexts', 'Understand the commutative property'],
    explanation: 'Multiplication facts 6-10 build on earlier learning. The commutative property means 6 × 7 = 7 × 6 = 42. Both arrangements give the same result.',
    examples: ['6 × 7 = 42', '8 × 9 = 72', '10 × 5 = 50'],
    summary: 'Multiplication facts 6-10 are essential. The order of numbers does not change the result.',
    difficulty: 'intermediate',
    duration: 15,
    order: 5,
  },
  {
    id: 'math-006',
    subject: 'Mathematics',
    category: 'Division',
    title: 'Introduction to Division',
    objectives: ['Understand division as sharing equally', 'Learn division facts related to multiplication', 'Solve simple division problems'],
    explanation: 'Division is splitting into equal groups. 12 ÷ 3 means dividing 12 into 3 equal groups, which gives 4 in each group. Division is the opposite of multiplication.',
    examples: ['12 ÷ 3 = 4', '15 ÷ 5 = 3', '20 ÷ 4 = 5'],
    summary: 'Division splits a number into equal groups. It is the opposite of multiplication.',
    difficulty: 'intermediate',
    duration: 12,
    order: 6,
  },
  {
    id: 'math-007',
    subject: 'Mathematics',
    category: 'Fractions',
    title: 'Understanding Fractions',
    objectives: ['Understand what fractions represent', 'Identify numerator and denominator', 'Compare simple fractions'],
    explanation: 'A fraction shows a part of a whole. The numerator (top) shows how many parts we have, and the denominator (bottom) shows how many equal parts the whole is divided into. 1/2 means 1 part out of 2 equal parts.',
    examples: ['1/2 = one half', '1/4 = one quarter', '3/4 = three quarters'],
    summary: 'Fractions represent parts of a whole. The numerator is the part, the denominator is the total.',
    difficulty: 'intermediate',
    duration: 12,
    order: 7,
  },
  {
    id: 'math-008',
    subject: 'Mathematics',
    category: 'Decimals',
    title: 'Introduction to Decimals',
    objectives: ['Understand decimal notation', 'Connect decimals to fractions', 'Read and write decimal numbers'],
    explanation: 'Decimals are another way to show parts of a whole. 0.5 means 5 tenths, which equals 1/2. The decimal point separates the whole number from the fractional part.',
    examples: ['0.5 = 5 tenths = 1/2', '0.25 = 25 hundredths = 1/4', '0.75 = 75 hundredths = 3/4'],
    summary: 'Decimals use a decimal point to show tenths, hundredths, and other fractional parts.',
    difficulty: 'intermediate',
    duration: 12,
    order: 8,
  },
  {
    id: 'math-009',
    subject: 'Mathematics',
    category: 'Geometry',
    title: 'Basic Shapes and Properties',
    objectives: ['Identify basic 2D shapes', 'Understand shape properties', 'Classify shapes by characteristics'],
    explanation: 'Shapes have different properties. A triangle has 3 sides and 3 angles. A square has 4 equal sides and 4 right angles. A circle has no sides or angles.',
    examples: ['Triangle: 3 sides, 3 angles', 'Square: 4 equal sides, 4 right angles', 'Circle: 0 sides, 0 angles'],
    summary: 'Each shape has unique properties that help us identify and classify it.',
    difficulty: 'beginner',
    duration: 10,
    order: 9,
  },
  {
    id: 'math-010',
    subject: 'Mathematics',
    category: 'Geometry',
    title: 'Perimeter and Area',
    objectives: ['Calculate perimeter of shapes', 'Calculate area of rectangles', 'Understand the difference between perimeter and area'],
    explanation: 'Perimeter is the distance around a shape (add all sides). Area is the space inside a shape. For a rectangle, area = length × width.',
    examples: ['Rectangle 5×3: Perimeter = 16, Area = 15', 'Square 4×4: Perimeter = 16, Area = 16'],
    summary: 'Perimeter measures around a shape. Area measures the space inside.',
    difficulty: 'intermediate',
    duration: 12,
    order: 10,
  },
  {
    id: 'math-011',
    subject: 'Mathematics',
    category: 'Measurement',
    title: 'Units of Measurement',
    objectives: ['Understand different units of length', 'Convert between units', 'Measure objects accurately'],
    explanation: 'Different units measure length: millimeters (mm), centimeters (cm), meters (m), kilometers (km). 1 cm = 10 mm, 1 m = 100 cm, 1 km = 1000 m.',
    examples: ['A pencil is about 19 cm long', 'A classroom is about 10 m long', 'A city is measured in kilometers'],
    summary: 'Different units measure different distances. Larger distances use larger units.',
    difficulty: 'beginner',
    duration: 10,
    order: 11,
  },
  {
    id: 'math-012',
    subject: 'Mathematics',
    category: 'Measurement',
    title: 'Time and Clocks',
    objectives: ['Read analog and digital clocks', 'Understand hours and minutes', 'Calculate elapsed time'],
    explanation: 'A clock shows time. The hour hand (short) shows hours, the minute hand (long) shows minutes. 60 minutes = 1 hour. Digital clocks show time as numbers.',
    examples: ['3:30 means 3 hours and 30 minutes', 'Half past three', 'Quarter to four is 3:45'],
    summary: 'Clocks show time using hours and minutes. Both analog and digital formats show the same time.',
    difficulty: 'beginner',
    duration: 12,
    order: 12,
  },
  {
    id: 'math-013',
    subject: 'Mathematics',
    category: 'Data',
    title: 'Graphs and Charts',
    objectives: ['Read bar graphs', 'Interpret data from charts', 'Create simple graphs'],
    explanation: 'Graphs show information visually. Bar graphs use bars to compare amounts. Line graphs show changes over time. Pie charts show parts of a whole.',
    examples: ['A bar graph showing favorite fruits', 'A line graph showing temperature changes', 'A pie chart showing how time is spent'],
    summary: 'Graphs help us understand and compare data visually.',
    difficulty: 'intermediate',
    duration: 12,
    order: 13,
  },
  {
    id: 'math-014',
    subject: 'Mathematics',
    category: 'Money',
    title: 'Understanding Money',
    objectives: ['Identify coins and notes', 'Calculate total amounts', 'Make change'],
    explanation: 'Money comes in different denominations: coins (1¢, 5¢, 10¢, 25¢) and notes ($1, $5, $10, etc.). To find total money, add all values.',
    examples: ['2 dimes + 3 nickels = 35¢', '1 quarter + 2 dimes = 45¢', '$5 + $3 = $8'],
    summary: 'Different coins and notes have different values. Add them to find the total amount.',
    difficulty: 'beginner',
    duration: 10,
    order: 14,
  },
  {
    id: 'math-015',
    subject: 'Mathematics',
    category: 'Problem Solving',
    title: 'Word Problems and Problem Solving',
    objectives: ['Read and understand word problems', 'Identify what is being asked', 'Choose the right operation', 'Solve multi-step problems'],
    explanation: 'Word problems describe real situations using words. Read carefully, identify what you know and what you need to find, then choose the right operation (add, subtract, multiply, or divide).',
    examples: ['If you have 5 apples and get 3 more, how many do you have? (5+3=8)', 'If 12 cookies are shared equally among 3 friends, how many does each get? (12÷3=4)'],
    summary: 'Word problems connect math to real life. Read carefully and choose the right operation.',
    difficulty: 'intermediate',
    duration: 15,
    order: 15,
  },

  // SCIENCE (12 lessons)
  {
    id: 'sci-001',
    subject: 'Science',
    category: 'Life Science',
    title: 'Living and Non-Living Things',
    objectives: ['Distinguish between living and non-living things', 'Identify characteristics of life', 'Classify objects'],
    explanation: 'Living things grow, move, eat, breathe, and reproduce. Non-living things do not have these characteristics. Plants and animals are living. Rocks and water are non-living.',
    examples: ['Living: dog, tree, flower, human', 'Non-living: rock, water, chair, book'],
    summary: 'Living things have characteristics like growth and movement. Non-living things do not.',
    difficulty: 'beginner',
    duration: 10,
    order: 1,
  },
  {
    id: 'sci-002',
    subject: 'Science',
    category: 'Life Science',
    title: 'Plant Life Cycle',
    objectives: ['Understand the plant life cycle', 'Identify stages of growth', 'Understand plant needs'],
    explanation: 'Plants go through stages: seed, sprout, growth, flowering, and reproduction. Plants need water, sunlight, and soil to grow. Seeds contain baby plants and stored food.',
    examples: ['Bean seed grows into a bean plant', 'Sunflower seed becomes a sunflower', 'Tomato plant produces tomatoes'],
    summary: 'Plants grow from seeds through several stages. They need water, light, and soil.',
    difficulty: 'beginner',
    duration: 12,
    order: 2,
  },
  {
    id: 'sci-003',
    subject: 'Science',
    category: 'Life Science',
    title: 'Animal Classification',
    objectives: ['Classify animals into groups', 'Understand animal characteristics', 'Identify vertebrates and invertebrates'],
    explanation: 'Animals are classified by their characteristics. Mammals have hair and feed milk to babies. Birds have feathers and lay eggs. Fish have scales and live in water. Reptiles have scales and are cold-blooded. Insects have six legs.',
    examples: ['Mammals: dog, cat, human', 'Birds: eagle, penguin, sparrow', 'Fish: salmon, goldfish', 'Reptiles: snake, lizard', 'Insects: butterfly, ant, bee'],
    summary: 'Animals are grouped by shared characteristics like body covering, how they reproduce, and where they live.',
    difficulty: 'beginner',
    duration: 12,
    order: 3,
  },
  {
    id: 'sci-004',
    subject: 'Science',
    category: 'Life Science',
    title: 'Food Chains and Food Webs',
    objectives: ['Understand food chains', 'Identify producers and consumers', 'Understand energy transfer'],
    explanation: 'A food chain shows how energy moves through nature. Plants (producers) make their own food. Herbivores eat plants. Carnivores eat herbivores. Decomposers break down dead material.',
    examples: ['Grass → Rabbit → Fox', 'Plant → Insect → Bird', 'Algae → Fish → Pelican'],
    summary: 'Food chains show how energy moves from plants to animals. Each organism depends on others.',
    difficulty: 'intermediate',
    duration: 12,
    order: 4,
  },
  {
    id: 'sci-005',
    subject: 'Science',
    category: 'Earth Science',
    title: 'The Water Cycle',
    objectives: ['Understand the water cycle', 'Identify evaporation, condensation, and precipitation', 'Understand water movement'],
    explanation: 'Water cycles through nature: evaporation (water becomes vapor), condensation (vapor becomes water), and precipitation (water falls as rain). This cycle repeats continuously.',
    examples: ['Water from ocean evaporates', 'Water vapor condenses into clouds', 'Rain falls back to earth'],
    summary: 'Water continuously cycles between earth and atmosphere through evaporation, condensation, and precipitation.',
    difficulty: 'intermediate',
    duration: 12,
    order: 5,
  },
  {
    id: 'sci-006',
    subject: 'Science',
    category: 'Earth Science',
    title: 'Weather and Climate',
    objectives: ['Understand weather patterns', 'Distinguish weather from climate', 'Identify weather types'],
    explanation: 'Weather is the daily condition of the atmosphere (temperature, precipitation, wind). Climate is the average weather over many years. Different regions have different climates.',
    examples: ['Weather: sunny today, rainy tomorrow', 'Climate: tropical, desert, temperate'],
    summary: 'Weather changes daily. Climate is the average weather pattern over years.',
    difficulty: 'beginner',
    duration: 10,
    order: 6,
  },
  {
    id: 'sci-007',
    subject: 'Science',
    category: 'Earth Science',
    title: 'Rocks and Minerals',
    objectives: ['Identify types of rocks', 'Understand rock formation', 'Distinguish rocks from minerals'],
    explanation: 'Rocks are made of minerals. Igneous rocks form from cooled magma. Sedimentary rocks form from compressed sediment. Metamorphic rocks form under heat and pressure.',
    examples: ['Granite is igneous', 'Sandstone is sedimentary', 'Marble is metamorphic'],
    summary: 'Rocks form in different ways and have different properties. Minerals are the building blocks of rocks.',
    difficulty: 'intermediate',
    duration: 12,
    order: 7,
  },
  {
    id: 'sci-008',
    subject: 'Science',
    category: 'Physical Science',
    title: 'States of Matter',
    objectives: ['Understand solid, liquid, and gas', 'Identify properties of each state', 'Understand phase changes'],
    explanation: 'Matter exists in three states: solid (fixed shape and volume), liquid (fixed volume, takes container shape), and gas (no fixed shape or volume). Heat can change states.',
    examples: ['Ice is solid water', 'Water is liquid', 'Steam is gaseous water'],
    summary: 'Matter can be solid, liquid, or gas. Heat can change matter from one state to another.',
    difficulty: 'beginner',
    duration: 10,
    order: 8,
  },
  {
    id: 'sci-009',
    subject: 'Science',
    category: 'Physical Science',
    title: 'Energy and Motion',
    objectives: ['Understand energy types', 'Understand forces and motion', 'Apply Newton\'s laws'],
    explanation: 'Energy is the ability to do work. Kinetic energy is motion. Potential energy is stored. Forces cause motion. Newton\'s first law: objects move unless a force stops them.',
    examples: ['A moving ball has kinetic energy', 'A ball at the top of a hill has potential energy', 'Friction is a force that slows motion'],
    summary: 'Energy and forces cause motion. Different types of energy can be converted.',
    difficulty: 'intermediate',
    duration: 12,
    order: 9,
  },
  {
    id: 'sci-010',
    subject: 'Science',
    category: 'Physical Science',
    title: 'Light and Sound',
    objectives: ['Understand light properties', 'Understand sound properties', 'Understand reflection and refraction'],
    explanation: 'Light travels in straight lines and can reflect (bounce) and refract (bend). Sound travels in waves through air. Light travels faster than sound.',
    examples: ['Mirror reflects light', 'Prism bends light into colors', 'Thunder is sound from lightning'],
    summary: 'Light and sound are forms of energy that travel as waves. They have different speeds and properties.',
    difficulty: 'intermediate',
    duration: 12,
    order: 10,
  },
  {
    id: 'sci-011',
    subject: 'Science',
    category: 'Physical Science',
    title: 'Simple Machines',
    objectives: ['Identify simple machines', 'Understand how machines work', 'Calculate mechanical advantage'],
    explanation: 'Simple machines help us do work: lever, pulley, inclined plane, wedge, screw, wheel and axle. They reduce the effort needed or change the direction of force.',
    examples: ['Lever: seesaw, crowbar', 'Pulley: flagpole', 'Inclined plane: ramp', 'Wedge: knife', 'Screw: bolt', 'Wheel and axle: bicycle'],
    summary: 'Simple machines make work easier by reducing effort or changing force direction.',
    difficulty: 'intermediate',
    duration: 12,
    order: 11,
  },
  {
    id: 'sci-012',
    subject: 'Science',
    category: 'Space Science',
    title: 'The Solar System',
    objectives: ['Understand the solar system', 'Identify planets', 'Understand Earth\'s place in space'],
    explanation: 'The solar system contains the Sun and 8 planets. Mercury, Venus, Earth, and Mars are inner planets. Jupiter, Saturn, Uranus, and Neptune are outer planets. Earth orbits the Sun.',
    examples: ['Mercury is closest to the Sun', 'Earth is third from the Sun', 'Jupiter is the largest planet'],
    summary: 'The solar system contains the Sun and planets. Earth orbits the Sun, and the Moon orbits Earth.',
    difficulty: 'beginner',
    duration: 12,
    order: 12,
  },

  // ENGLISH (12 lessons)
  {
    id: 'eng-001',
    subject: 'English',
    category: 'Grammar',
    title: 'Nouns and Pronouns',
    objectives: ['Identify nouns', 'Understand pronouns', 'Use pronouns correctly'],
    explanation: 'A noun is a person, place, or thing. Pronouns replace nouns: I, you, he, she, it, we, they. Using pronouns makes writing less repetitive.',
    examples: ['Noun: dog, city, happiness', 'Pronoun: he, she, it, they', 'Instead of "John is tall," say "He is tall"'],
    summary: 'Nouns name things. Pronouns replace nouns to avoid repetition.',
    difficulty: 'beginner',
    duration: 10,
    order: 1,
  },
  {
    id: 'eng-002',
    subject: 'English',
    category: 'Grammar',
    title: 'Verbs and Tenses',
    objectives: ['Identify verbs', 'Understand verb tenses', 'Use correct tense'],
    explanation: 'A verb is an action word. Tenses show when an action happens: past (happened), present (happening now), future (will happen). Regular verbs add -ed for past tense.',
    examples: ['Present: I run', 'Past: I ran', 'Future: I will run'],
    summary: 'Verbs show action. Tenses show when the action happens.',
    difficulty: 'beginner',
    duration: 10,
    order: 2,
  },
  {
    id: 'eng-003',
    subject: 'English',
    category: 'Grammar',
    title: 'Adjectives and Adverbs',
    objectives: ['Identify adjectives', 'Identify adverbs', 'Use them correctly'],
    explanation: 'Adjectives describe nouns (big, red, happy). Adverbs describe verbs and adjectives (quickly, very, slowly). Adverbs often end in -ly.',
    examples: ['Adjective: big dog, red car', 'Adverb: runs quickly, very happy', 'He spoke loudly'],
    summary: 'Adjectives describe nouns. Adverbs describe actions and other adjectives.',
    difficulty: 'intermediate',
    duration: 10,
    order: 3,
  },
  {
    id: 'eng-004',
    subject: 'English',
    category: 'Grammar',
    title: 'Sentences and Punctuation',
    objectives: ['Understand sentence structure', 'Use correct punctuation', 'Identify sentence types'],
    explanation: 'A sentence has a subject and verb. Punctuation marks: period (.), question mark (?), exclamation mark (!), comma (,). Different punctuation shows different sentence types.',
    examples: ['Statement: The cat is sleeping.', 'Question: Is the cat sleeping?', 'Exclamation: The cat is sleeping!'],
    summary: 'Sentences need correct punctuation. Different marks show different sentence types.',
    difficulty: 'beginner',
    duration: 10,
    order: 4,
  },
  {
    id: 'eng-005',
    subject: 'English',
    category: 'Vocabulary',
    title: 'Synonyms and Antonyms',
    objectives: ['Understand synonyms', 'Understand antonyms', 'Use them in writing'],
    explanation: 'Synonyms are words with similar meanings (big, large). Antonyms are words with opposite meanings (big, small). Using synonyms makes writing more interesting.',
    examples: ['Synonyms: happy/joyful, fast/quick', 'Antonyms: hot/cold, big/small', 'Instead of "big" twice, use "big" and "large"'],
    summary: 'Synonyms have similar meanings. Antonyms have opposite meanings.',
    difficulty: 'intermediate',
    duration: 10,
    order: 5,
  },
  {
    id: 'eng-006',
    subject: 'English',
    category: 'Vocabulary',
    title: 'Prefixes and Suffixes',
    objectives: ['Understand common prefixes', 'Understand common suffixes', 'Build new words'],
    explanation: 'Prefixes are added to the beginning of words (un-, re-, pre-). Suffixes are added to the end (-ing, -ed, -tion). They change word meaning or form.',
    examples: ['Prefix: unhappy, redo, preview', 'Suffix: running, jumped, action'],
    summary: 'Prefixes and suffixes modify word meaning. They help us build and understand new words.',
    difficulty: 'intermediate',
    duration: 10,
    order: 6,
  },
  {
    id: 'eng-007',
    subject: 'English',
    category: 'Reading',
    title: 'Main Idea and Supporting Details',
    objectives: ['Identify main idea', 'Find supporting details', 'Understand text structure'],
    explanation: 'The main idea is the most important point. Supporting details provide information about the main idea. Good readers identify both to understand the text.',
    examples: ['Main idea: Cats are independent animals', 'Detail: Cats groom themselves', 'Detail: Cats hunt alone'],
    summary: 'The main idea is the central point. Supporting details explain and support it.',
    difficulty: 'intermediate',
    duration: 12,
    order: 7,
  },
  {
    id: 'eng-008',
    subject: 'English',
    category: 'Reading',
    title: 'Inference and Prediction',
    objectives: ['Make inferences', 'Make predictions', 'Use evidence from text'],
    explanation: 'An inference is a conclusion based on evidence. A prediction is a guess about what will happen next. Both use information from the text and prior knowledge.',
    examples: ['Text: "She wore a heavy coat." Inference: It was cold', 'Prediction: She will go outside'],
    summary: 'Inferences and predictions use text evidence and prior knowledge to understand and anticipate.',
    difficulty: 'intermediate',
    duration: 12,
    order: 8,
  },
  {
    id: 'eng-009',
    subject: 'English',
    category: 'Writing',
    title: 'Writing Paragraphs',
    objectives: ['Write topic sentences', 'Develop ideas', 'Write concluding sentences'],
    explanation: 'A paragraph has a topic sentence (main idea), supporting sentences (details), and a concluding sentence. All sentences relate to the topic.',
    examples: ['Topic: Dogs are loyal pets', 'Support: They protect families, they show affection', 'Conclusion: Dogs make wonderful companions'],
    summary: 'Paragraphs have a clear structure: topic, supporting details, and conclusion.',
    difficulty: 'intermediate',
    duration: 12,
    order: 9,
  },
  {
    id: 'eng-010',
    subject: 'English',
    category: 'Writing',
    title: 'Story Writing',
    objectives: ['Write stories with clear structure', 'Create characters', 'Develop plot'],
    explanation: 'Stories have a beginning (introduction), middle (conflict/action), and end (resolution). Good stories have interesting characters and a clear plot.',
    examples: ['Beginning: Introduce character and setting', 'Middle: Character faces a problem', 'End: Problem is solved'],
    summary: 'Stories need clear structure with beginning, middle, and end. Characters and plot make stories interesting.',
    difficulty: 'intermediate',
    duration: 15,
    order: 10,
  },
  {
    id: 'eng-011',
    subject: 'English',
    category: 'Communication',
    title: 'Speaking and Listening',
    objectives: ['Speak clearly', 'Listen actively', 'Communicate effectively'],
    explanation: 'Good speakers speak clearly and organize their thoughts. Good listeners pay attention and ask questions. Effective communication requires both.',
    examples: ['Speak: Use clear voice, make eye contact', 'Listen: Face the speaker, nod, ask questions'],
    summary: 'Good communication requires clear speaking and active listening.',
    difficulty: 'beginner',
    duration: 10,
    order: 11,
  },
  {
    id: 'eng-012',
    subject: 'English',
    category: 'Literature',
    title: 'Fables and Folktales',
    objectives: ['Understand fables', 'Identify morals', 'Understand cultural stories'],
    explanation: 'Fables are short stories with animals that teach a lesson (moral). Folktales are traditional stories passed down through cultures. Both teach values and lessons.',
    examples: ['Fable: The Tortoise and the Hare (slow and steady wins)', 'Folktale: Cinderella (kindness is rewarded)'],
    summary: 'Fables and folktales teach lessons through stories. They reflect cultural values and wisdom.',
    difficulty: 'beginner',
    duration: 12,
    order: 12,
  },

  // CODING (10 lessons)
  {
    id: 'code-001',
    subject: 'Coding',
    category: 'Basics',
    title: 'Introduction to Programming',
    objectives: ['Understand what programming is', 'Learn basic programming concepts', 'Understand algorithms'],
    explanation: 'Programming is giving instructions to computers. Programs are step-by-step instructions. An algorithm is a plan for solving a problem. Programs follow algorithms.',
    examples: ['Algorithm: Steps to make a sandwich', 'Program: Code that follows the algorithm', 'Computer: Executes the program'],
    summary: 'Programming is creating step-by-step instructions for computers. Algorithms are the plans.',
    difficulty: 'beginner',
    duration: 12,
    order: 1,
  },
  {
    id: 'code-002',
    subject: 'Coding',
    category: 'Basics',
    title: 'Variables and Data Types',
    objectives: ['Understand variables', 'Learn data types', 'Store and use data'],
    explanation: 'Variables store information. Data types include numbers (integers, decimals), text (strings), and true/false (booleans). Variables have names and hold values.',
    examples: ['age = 10 (integer)', 'name = "Alice" (string)', 'isStudent = true (boolean)'],
    summary: 'Variables store data. Different data types store different kinds of information.',
    difficulty: 'beginner',
    duration: 12,
    order: 2,
  },
  {
    id: 'code-003',
    subject: 'Coding',
    category: 'Basics',
    title: 'Operators and Expressions',
    objectives: ['Understand operators', 'Create expressions', 'Calculate results'],
    explanation: 'Operators perform actions: arithmetic (+, -, *, /), comparison (>, <, ==), logical (and, or). Expressions combine variables and operators.',
    examples: ['5 + 3 = 8', 'age > 10 (true or false)', 'x = 10 and y = 5'],
    summary: 'Operators perform actions on data. Expressions combine data and operators.',
    difficulty: 'beginner',
    duration: 12,
    order: 3,
  },
  {
    id: 'code-004',
    subject: 'Coding',
    category: 'Control Flow',
    title: 'If Statements and Conditions',
    objectives: ['Understand conditional logic', 'Write if statements', 'Make decisions in code'],
    explanation: 'If statements make decisions. If a condition is true, code runs. If false, it skips. Else statements run when if is false.',
    examples: ['if age > 10: print("You are old enough")', 'if score > 80: print("Pass") else: print("Fail")'],
    summary: 'If statements make decisions based on conditions. Code runs or skips based on true/false.',
    difficulty: 'intermediate',
    duration: 12,
    order: 4,
  },
  {
    id: 'code-005',
    subject: 'Coding',
    category: 'Control Flow',
    title: 'Loops and Repetition',
    objectives: ['Understand loops', 'Write for and while loops', 'Repeat code efficiently'],
    explanation: 'Loops repeat code. For loops repeat a set number of times. While loops repeat while a condition is true. Loops save time and code.',
    examples: ['for i in range(5): print(i)', 'while x < 10: x = x + 1'],
    summary: 'Loops repeat code. For loops repeat a set number of times. While loops repeat until a condition is false.',
    difficulty: 'intermediate',
    duration: 12,
    order: 5,
  },
  {
    id: 'code-006',
    subject: 'Coding',
    category: 'Functions',
    title: 'Functions and Procedures',
    objectives: ['Understand functions', 'Write functions', 'Use functions to organize code'],
    explanation: 'Functions are reusable blocks of code. They take input (parameters) and return output. Functions make code organized and avoid repetition.',
    examples: ['def greet(name): return "Hello " + name', 'def add(a, b): return a + b'],
    summary: 'Functions are reusable blocks of code. They organize code and avoid repetition.',
    difficulty: 'intermediate',
    duration: 12,
    order: 6,
  },
  {
    id: 'code-007',
    subject: 'Coding',
    category: 'Data Structures',
    title: 'Lists and Arrays',
    objectives: ['Understand lists', 'Access list elements', 'Modify lists'],
    explanation: 'Lists store multiple values. Each value has an index (position). Lists can be modified by adding, removing, or changing elements.',
    examples: ['fruits = ["apple", "banana", "orange"]', 'fruits[0] = "apple"', 'fruits.append("grape")'],
    summary: 'Lists store multiple values. Each has an index. Lists can be modified.',
    difficulty: 'intermediate',
    duration: 12,
    order: 7,
  },
  {
    id: 'code-008',
    subject: 'Coding',
    category: 'Data Structures',
    title: 'Dictionaries and Objects',
    objectives: ['Understand dictionaries', 'Store key-value pairs', 'Access dictionary data'],
    explanation: 'Dictionaries store data as key-value pairs. Keys are unique identifiers. Values are the data. Dictionaries are useful for organizing related data.',
    examples: ['person = {"name": "Alice", "age": 10}', 'person["name"] = "Alice"'],
    summary: 'Dictionaries store key-value pairs. Keys identify values. Useful for organizing related data.',
    difficulty: 'intermediate',
    duration: 12,
    order: 8,
  },
  {
    id: 'code-009',
    subject: 'Coding',
    category: 'Problem Solving',
    title: 'Debugging and Error Handling',
    objectives: ['Find and fix errors', 'Understand error types', 'Debug code'],
    explanation: 'Errors happen in code. Syntax errors break the code. Logic errors make code run wrong. Debugging is finding and fixing errors. Error handling prevents crashes.',
    examples: ['Syntax error: missing colon', 'Logic error: wrong calculation', 'Try/except: handle errors gracefully'],
    summary: 'Debugging finds and fixes errors. Error handling prevents crashes.',
    difficulty: 'intermediate',
    duration: 12,
    order: 9,
  },
  {
    id: 'code-010',
    subject: 'Coding',
    category: 'Projects',
    title: 'Building Simple Programs',
    objectives: ['Combine concepts', 'Build working programs', 'Solve real problems'],
    explanation: 'Real programs combine variables, operators, conditionals, loops, and functions. Start small and build up. Test and debug as you go.',
    examples: ['Calculator: take input, perform operation, show result', 'Quiz game: ask questions, check answers, keep score'],
    summary: 'Real programs combine multiple concepts. Start simple and build up.',
    difficulty: 'intermediate',
    duration: 15,
    order: 10,
  },

  // GEOGRAPHY (8 lessons)
  {
    id: 'geo-001',
    subject: 'Geography',
    category: 'Maps',
    title: 'Understanding Maps',
    objectives: ['Read maps', 'Understand map symbols', 'Use map scales'],
    explanation: 'Maps show Earth\'s surface. Symbols represent features (mountains, rivers, cities). Scale shows distances. Compass rose shows directions (N, S, E, W).',
    examples: ['Symbol: mountain triangle', 'Scale: 1 inch = 10 miles', 'Compass: North is up'],
    summary: 'Maps show Earth\'s features using symbols and scales. Compass roses show directions.',
    difficulty: 'beginner',
    duration: 10,
    order: 1,
  },
  {
    id: 'geo-002',
    subject: 'Geography',
    category: 'Continents',
    title: 'Continents and Oceans',
    objectives: ['Identify continents', 'Identify oceans', 'Understand Earth\'s geography'],
    explanation: 'Earth has 7 continents: Africa, Antarctica, Asia, Europe, North America, Oceania, South America. Five oceans cover Earth: Pacific, Atlantic, Indian, Arctic, Southern.',
    examples: ['Largest continent: Asia', 'Largest ocean: Pacific', 'Smallest continent: Antarctica'],
    summary: 'Earth has 7 continents and 5 oceans. Continents are land. Oceans are water.',
    difficulty: 'beginner',
    duration: 10,
    order: 2,
  },
  {
    id: 'geo-003',
    subject: 'Geography',
    category: 'Landforms',
    title: 'Landforms and Features',
    objectives: ['Identify landforms', 'Understand how they form', 'Recognize features'],
    explanation: 'Landforms include mountains (high peaks), valleys (low areas), plains (flat areas), plateaus (high flat areas), and canyons (deep cuts). Rivers, lakes, and coasts are water features.',
    examples: ['Mountain: Mount Everest', 'Valley: Grand Canyon', 'Plain: Great Plains', 'River: Amazon'],
    summary: 'Landforms are natural features of Earth\'s surface. They form through natural processes.',
    difficulty: 'beginner',
    duration: 10,
    order: 3,
  },
  {
    id: 'geo-004',
    subject: 'Geography',
    category: 'Countries',
    title: 'Countries and Capitals',
    objectives: ['Identify countries', 'Learn capital cities', 'Understand political geography'],
    explanation: 'Countries are independent nations with governments. Capitals are major cities where governments meet. Each country has unique culture, language, and government.',
    examples: ['Country: France, Capital: Paris', 'Country: Japan, Capital: Tokyo', 'Country: Brazil, Capital: Brasília'],
    summary: 'Countries are independent nations. Capitals are important cities.',
    difficulty: 'beginner',
    duration: 12,
    order: 4,
  },
  {
    id: 'geo-005',
    subject: 'Geography',
    category: 'Climate',
    title: 'Climate Zones',
    objectives: ['Understand climate zones', 'Identify characteristics', 'Understand climate factors'],
    explanation: 'Climate zones depend on latitude and geography. Tropical zones are hot and wet. Temperate zones have seasons. Polar zones are cold. Deserts are dry.',
    examples: ['Tropical: rainforests, hot', 'Temperate: seasons, moderate', 'Polar: ice, very cold', 'Desert: dry, hot days'],
    summary: 'Climate zones have different temperatures and precipitation. Location determines climate.',
    difficulty: 'intermediate',
    duration: 12,
    order: 5,
  },
  {
    id: 'geo-006',
    subject: 'Geography',
    category: 'Resources',
    title: 'Natural Resources',
    objectives: ['Identify natural resources', 'Understand resource use', 'Understand sustainability'],
    explanation: 'Natural resources are materials from nature: water, soil, minerals, forests, fossil fuels. Renewable resources regrow (forests, water). Non-renewable resources don\'t (coal, oil).',
    examples: ['Renewable: trees, water, wind', 'Non-renewable: coal, oil, natural gas'],
    summary: 'Natural resources are materials from nature. Some are renewable, others are not.',
    difficulty: 'intermediate',
    duration: 12,
    order: 6,
  },
  {
    id: 'geo-007',
    subject: 'Geography',
    category: 'Culture',
    title: 'Culture and Diversity',
    objectives: ['Understand culture', 'Appreciate diversity', 'Learn about different cultures'],
    explanation: 'Culture includes language, religion, food, art, and traditions. Different regions have different cultures. Understanding culture helps us appreciate diversity.',
    examples: ['Language: English, Spanish, Mandarin', 'Food: pizza, sushi, curry', 'Tradition: holidays, celebrations'],
    summary: 'Culture is the way people live. Different regions have different cultures and traditions.',
    difficulty: 'beginner',
    duration: 10,
    order: 7,
  },
  {
    id: 'geo-008',
    subject: 'Geography',
    category: 'Human Geography',
    title: 'Population and Cities',
    objectives: ['Understand population', 'Learn about cities', 'Understand urbanization'],
    explanation: 'Population is the number of people. Cities are large population centers. Urbanization is the growth of cities. Different regions have different population densities.',
    examples: ['Largest city: Tokyo', 'Most populous country: India', 'Least populous continent: Antarctica'],
    summary: 'Population varies by region. Cities are centers of population and activity.',
    difficulty: 'intermediate',
    duration: 12,
    order: 8,
  },

  // HISTORY (8 lessons)
  {
    id: 'hist-001',
    subject: 'History',
    category: 'Ancient',
    title: 'Ancient Civilizations',
    objectives: ['Learn about ancient civilizations', 'Understand historical periods', 'Recognize contributions'],
    explanation: 'Ancient civilizations developed complex societies: Egypt (pyramids), Mesopotamia (writing), Greece (philosophy), Rome (government). They made lasting contributions.',
    examples: ['Egypt: pyramids, hieroglyphics', 'Greece: democracy, philosophy', 'Rome: government, engineering'],
    summary: 'Ancient civilizations developed writing, government, and engineering. Their contributions shape us today.',
    difficulty: 'intermediate',
    duration: 12,
    order: 1,
  },
  {
    id: 'hist-002',
    subject: 'History',
    category: 'Medieval',
    title: 'Medieval Period',
    objectives: ['Understand the Medieval period', 'Learn about feudalism', 'Understand social structure'],
    explanation: 'The Medieval period (Middle Ages) followed Rome\'s fall. Feudalism was the social system: kings, nobles, knights, peasants. Castles and churches were important.',
    examples: ['King: ruled the kingdom', 'Noble: owned land', 'Knight: protected land', 'Peasant: worked the land'],
    summary: 'The Medieval period had a feudal system with kings, nobles, knights, and peasants.',
    difficulty: 'intermediate',
    duration: 12,
    order: 2,
  },
  {
    id: 'hist-003',
    subject: 'History',
    category: 'Exploration',
    title: 'Age of Exploration',
    objectives: ['Learn about exploration', 'Understand discovery', 'Understand global impact'],
    explanation: 'The Age of Exploration (1400s-1600s) saw Europeans explore the world. Columbus reached America. Explorers mapped oceans and continents. This changed the world.',
    examples: ['Columbus: sailed to America', 'Magellan: circumnavigated Earth', 'Da Gama: reached India by sea'],
    summary: 'Explorers traveled the world, discovering new lands and changing global connections.',
    difficulty: 'intermediate',
    duration: 12,
    order: 3,
  },
  {
    id: 'hist-004',
    subject: 'History',
    category: 'Revolution',
    title: 'American Revolution',
    objectives: ['Understand the American Revolution', 'Learn about independence', 'Understand democracy'],
    explanation: 'The American Revolution (1775-1783) created the United States. Colonists fought for independence from Britain. The Declaration of Independence stated their rights.',
    examples: ['Boston Tea Party: protest taxes', 'Declaration of Independence: stated rights', 'Constitution: created government'],
    summary: 'The American Revolution created an independent nation based on democratic principles.',
    difficulty: 'intermediate',
    duration: 12,
    order: 4,
  },
  {
    id: 'hist-005',
    subject: 'History',
    category: 'Industrial',
    title: 'Industrial Revolution',
    objectives: ['Understand the Industrial Revolution', 'Learn about technology', 'Understand social change'],
    explanation: 'The Industrial Revolution (1700s-1800s) brought machines and factories. Steam power, textiles, and steel changed production. Cities grew. Society changed dramatically.',
    examples: ['Steam engine: powered machines', 'Factories: mass production', 'Railroads: transportation', 'Cities: population growth'],
    summary: 'The Industrial Revolution brought machines and factories, changing production and society.',
    difficulty: 'intermediate',
    duration: 12,
    order: 5,
  },
  {
    id: 'hist-006',
    subject: 'History',
    category: 'Modern',
    title: 'World War I',
    objectives: ['Understand World War I', 'Learn about global conflict', 'Understand consequences'],
    explanation: 'World War I (1914-1918) involved most of Europe and beyond. Millions died. New weapons changed warfare. The war reshaped the world.',
    examples: ['Trench warfare: static battles', 'Machine guns: deadly weapons', 'Treaty of Versailles: ended war'],
    summary: 'World War I was a major global conflict that changed warfare and reshaped the world.',
    difficulty: 'intermediate',
    duration: 12,
    order: 6,
  },
  {
    id: 'hist-007',
    subject: 'History',
    category: 'Modern',
    title: 'World War II',
    objectives: ['Understand World War II', 'Learn about global conflict', 'Understand consequences'],
    explanation: 'World War II (1939-1945) involved most countries. Millions died. Technology advanced rapidly. The war created the modern world.',
    examples: ['Nazi Germany: fascism', 'Pearl Harbor: US enters war', 'Atomic bomb: new technology'],
    summary: 'World War II was a global conflict that shaped the modern world.',
    difficulty: 'intermediate',
    duration: 12,
    order: 7,
  },
  {
    id: 'hist-008',
    subject: 'History',
    category: 'Modern',
    title: 'Civil Rights Movement',
    objectives: ['Understand civil rights', 'Learn about equality', 'Understand social change'],
    explanation: 'The Civil Rights Movement (1950s-1960s) fought for equality. Leaders like Martin Luther King Jr. fought discrimination. Laws changed. Society progressed.',
    examples: ['Segregation: separated by race', 'Sit-ins: peaceful protest', 'Civil Rights Act: ended segregation'],
    summary: 'The Civil Rights Movement fought for equality and changed laws and society.',
    difficulty: 'intermediate',
    duration: 12,
    order: 8,
  },

  {
    id: 'tamil-001', subject: 'Tamil', category: 'Letters', title: 'Tamil Vowels — உயிரெழுத்துகள்',
    objectives: ['Recognise the 12 Tamil vowels', 'Pronounce common vowel sounds', 'Match letters with example words'],
    explanation: 'Tamil has 12 vowels called உயிரெழுத்துகள். They are அ, ஆ, இ, ஈ, உ, ஊ, எ, ஏ, ஐ, ஒ, ஓ, ஔ. Learning their shapes and sounds is the first step in reading Tamil.',
    examples: ['அ — அம்மா', 'ஆ — ஆடு', 'இ — இலை'],
    summary: 'The 12 உயிரெழுத்துகள் are independent vowel letters used throughout Tamil words.',
    difficulty: 'beginner', duration: 12, order: 1,
  },
  {
    id: 'tamil-002', subject: 'Tamil', category: 'Words', title: 'Everyday Tamil Words',
    objectives: ['Read familiar Tamil words', 'Connect words to everyday objects', 'Practise clear pronunciation'],
    explanation: 'Begin with short words used at home and school. Look at each letter, say the sounds slowly, and then blend them into the whole word.',
    examples: ['மரம் — tree', 'பால் — milk', 'பள்ளி — school'],
    summary: 'Reading familiar words builds confidence and connects Tamil letters with meaning.',
    difficulty: 'beginner', duration: 10, order: 2,
  },
  {
    id: 'tamil-003', subject: 'Tamil', category: 'Sentences', title: 'Building a Simple Tamil Sentence',
    objectives: ['Identify subject and action', 'Arrange words in a clear sentence', 'Write one simple sentence'],
    explanation: 'A simple Tamil sentence often names a person or thing and then describes an action. For example, “குமார் பள்ளிக்குச் செல்கிறான்” means “Kumar goes to school.”',
    examples: ['நான் படிக்கிறேன் — I am reading', 'அவள் பாடுகிறாள் — She is singing', 'பூனை ஓடுகிறது — The cat runs'],
    summary: 'A clear sentence connects who or what with an action or description.',
    difficulty: 'intermediate', duration: 14, order: 3,
  },
  {
    id: 'music-001', subject: 'Music', category: 'Rhythm', title: 'Feeling a Steady Beat',
    objectives: ['Identify a steady beat', 'Clap along to a pulse', 'Distinguish beat from rhythm'],
    explanation: 'The beat is the steady pulse of music, like a clock ticking. Rhythm is the pattern of long and short sounds that happens over the beat.',
    examples: ['Clap once on every count: 1, 2, 3, 4', 'March evenly to a song', 'Tap the beat while speaking different rhythms'],
    summary: 'The beat stays steady while rhythms can change above it.',
    difficulty: 'beginner', duration: 10, order: 1,
  },
  {
    id: 'music-002', subject: 'Music', category: 'Pitch', title: 'High and Low Sounds',
    objectives: ['Recognise high and low pitch', 'Compare two sounds', 'Use voice safely to explore pitch'],
    explanation: 'Pitch describes how high or low a sound is. A small bell often has a higher pitch than a large drum. Melody is made by arranging different pitches.',
    examples: ['Bird chirp — usually high', 'Thunder — usually low', 'Sing a gentle glide from low to high'],
    summary: 'Pitch lets us describe and organise high and low sounds.',
    difficulty: 'beginner', duration: 10, order: 2,
  },
  {
    id: 'music-003', subject: 'Music', category: 'Instruments', title: 'Instrument Families',
    objectives: ['Name four instrument families', 'Explain how each family makes sound', 'Classify familiar instruments'],
    explanation: 'Common instrument families are strings, woodwind, brass and percussion. Instruments are grouped by how they create sound.',
    examples: ['Violin — strings', 'Flute — woodwind', 'Trumpet — brass', 'Drum — percussion'],
    summary: 'Instrument families help us understand how instruments make and shape sound.',
    difficulty: 'intermediate', duration: 12, order: 3,
  },
  {
    id: 'arts-001', subject: 'Arts', category: 'Colour', title: 'Primary and Secondary Colours',
    objectives: ['Name the primary colours', 'Mix secondary colours', 'Use colour choices intentionally'],
    explanation: 'In traditional paint mixing, red, yellow and blue are primary colours. Mixing two primary colours creates a secondary colour.',
    examples: ['Red + yellow = orange', 'Yellow + blue = green', 'Blue + red = purple'],
    summary: 'Primary colours can be mixed to make secondary colours.',
    difficulty: 'beginner', duration: 12, order: 1,
  },
  {
    id: 'arts-002', subject: 'Arts', category: 'Drawing', title: 'Drawing with Basic Shapes',
    objectives: ['Observe shapes in objects', 'Build a drawing from simple forms', 'Add detail after structure'],
    explanation: 'Many complex objects can be planned using circles, squares, rectangles and triangles. Start lightly with simple shapes, then refine the outline and details.',
    examples: ['House: square + triangle', 'Person: circles + lines', 'Tree: rectangle + cloud-like shapes'],
    summary: 'Breaking objects into basic shapes makes drawing easier and more accurate.',
    difficulty: 'beginner', duration: 15, order: 2,
  },
  {
    id: 'arts-003', subject: 'Arts', category: 'Composition', title: 'Foreground, Middle Ground and Background',
    objectives: ['Identify three picture areas', 'Create a sense of depth', 'Plan a balanced scene'],
    explanation: 'The foreground appears closest, the middle ground sits between, and the background appears farthest away. Size, overlap and placement help show depth.',
    examples: ['Large flower in foreground', 'House in middle ground', 'Mountains in background'],
    summary: 'Layering foreground, middle ground and background creates depth in an artwork.',
    difficulty: 'intermediate', duration: 15, order: 3,
  },
  {
    id: 'life-skills-001', subject: 'Life Skills', category: 'Communication', title: 'Active Listening',
    objectives: ['Give full attention', 'Ask useful follow-up questions', 'Summarise what was heard'],
    explanation: 'Active listening means focusing on the speaker, avoiding interruptions and checking that you understood. It helps people feel respected and reduces misunderstandings.',
    examples: ['Look towards the speaker', 'Ask “Could you explain that part?”', 'Say “So you mean…” to confirm'],
    summary: 'Active listening combines attention, respectful responses and understanding checks.',
    difficulty: 'beginner', duration: 10, order: 1,
  },
  {
    id: 'life-skills-002', subject: 'Life Skills', category: 'Organisation', title: 'Planning a Study Session',
    objectives: ['Choose a clear goal', 'Break work into short steps', 'Include a review and break'],
    explanation: 'A useful study plan starts with one realistic goal. Divide the task into small steps, remove distractions, work for a focused period and finish with a quick review.',
    examples: ['Goal: learn five new words', 'Work 20 minutes, break 5 minutes', 'Review mistakes before stopping'],
    summary: 'Clear goals, short focused steps and review make study time more effective.',
    difficulty: 'beginner', duration: 10, order: 2,
  },
  {
    id: 'life-skills-003', subject: 'Life Skills', category: 'Wellbeing', title: 'Handling a Difficult Emotion',
    objectives: ['Name an emotion', 'Use a calming pause', 'Choose a safe next action'],
    explanation: 'Strong emotions are normal. Pause, breathe slowly, name what you feel and choose a safe action such as talking to a trusted adult, writing it down or taking a short break.',
    examples: ['“I feel frustrated because…”', 'Take five slow breaths', 'Ask a trusted adult for help'],
    summary: 'Naming feelings and pausing can help you choose a safe, thoughtful response.',
    difficulty: 'beginner', duration: 10, order: 3,
  },

];
