export interface QuizQuestion {
  id: string;
  subject: string;
  lessonId: string;
  type: 'mcq' | 'true-false' | 'short-answer';
  question: string;
  options?: string[];
  correctAnswer: string | number;
  explanation: string;
  difficulty: 'easy' | 'medium' | 'hard';
}

export const quizzes: QuizQuestion[] = [
  // MATHEMATICS QUIZZES (12 questions)
  {
    id: 'quiz-math-001',
    subject: 'Mathematics',
    lessonId: 'math-001',
    type: 'mcq',
    question: 'In the number 456, what is the place value of 5?',
    options: ['5', '50', '500', '5000'],
    correctAnswer: 1,
    explanation: 'The 5 is in the tens place, so its value is 50.',
    difficulty: 'easy',
  },
  {
    id: 'quiz-math-002',
    subject: 'Mathematics',
    lessonId: 'math-002',
    type: 'mcq',
    question: 'What is 27 + 15?',
    options: ['32', '42', '52', '62'],
    correctAnswer: 1,
    explanation: 'Add ones: 7+5=12 (write 2, carry 1). Add tens: 2+1+1=4. Answer is 42.',
    difficulty: 'easy',
  },
  {
    id: 'quiz-math-003',
    subject: 'Mathematics',
    lessonId: 'math-003',
    type: 'mcq',
    question: 'What is 42 - 15?',
    options: ['17', '27', '37', '47'],
    correctAnswer: 1,
    explanation: 'Subtract ones: 2-5 requires borrowing. Borrow 1 ten: 12-5=7. Subtract tens: 3-1=2. Answer is 27.',
    difficulty: 'easy',
  },
  {
    id: 'quiz-math-004',
    subject: 'Mathematics',
    lessonId: 'math-004',
    type: 'mcq',
    question: 'What is 3 × 4?',
    options: ['7', '12', '14', '16'],
    correctAnswer: 1,
    explanation: '3 × 4 means 3 groups of 4, which is 4+4+4=12.',
    difficulty: 'easy',
  },
  {
    id: 'quiz-math-005',
    subject: 'Mathematics',
    lessonId: 'math-005',
    type: 'mcq',
    question: 'What is 6 × 7?',
    options: ['36', '42', '48', '54'],
    correctAnswer: 1,
    explanation: '6 × 7 = 42. This is a multiplication fact to memorize.',
    difficulty: 'medium',
  },
  {
    id: 'quiz-math-006',
    subject: 'Mathematics',
    lessonId: 'math-006',
    type: 'mcq',
    question: 'What is 12 ÷ 3?',
    options: ['2', '3', '4', '5'],
    correctAnswer: 2,
    explanation: '12 ÷ 3 means dividing 12 into 3 equal groups, which gives 4 in each group.',
    difficulty: 'easy',
  },
  {
    id: 'quiz-math-007',
    subject: 'Mathematics',
    lessonId: 'math-007',
    type: 'mcq',
    question: 'What fraction is shown if 1 part out of 4 equal parts is shaded?',
    options: ['1/2', '1/3', '1/4', '1/5'],
    correctAnswer: 2,
    explanation: 'If 1 part out of 4 equal parts is shaded, the fraction is 1/4.',
    difficulty: 'easy',
  },
  {
    id: 'quiz-math-008',
    subject: 'Mathematics',
    lessonId: 'math-008',
    type: 'mcq',
    question: 'What decimal is equal to 1/2?',
    options: ['0.2', '0.5', '0.75', '1.0'],
    correctAnswer: 1,
    explanation: '1/2 = 0.5 (five tenths).',
    difficulty: 'medium',
  },
  {
    id: 'quiz-math-009',
    subject: 'Mathematics',
    lessonId: 'math-009',
    type: 'true-false',
    question: 'A triangle has 4 sides.',
    options: ['True', 'False'],
    correctAnswer: 1,
    explanation: 'False. A triangle has 3 sides.',
    difficulty: 'easy',
  },
  {
    id: 'quiz-math-010',
    subject: 'Mathematics',
    lessonId: 'math-010',
    type: 'mcq',
    question: 'What is the perimeter of a rectangle with length 5 and width 3?',
    options: ['8', '15', '16', '25'],
    correctAnswer: 2,
    explanation: 'Perimeter = 2(length + width) = 2(5+3) = 2(8) = 16.',
    difficulty: 'medium',
  },
  {
    id: 'quiz-math-011',
    subject: 'Mathematics',
    lessonId: 'math-011',
    type: 'mcq',
    question: 'How many centimeters are in 1 meter?',
    options: ['10', '50', '100', '1000'],
    correctAnswer: 2,
    explanation: '1 meter = 100 centimeters.',
    difficulty: 'easy',
  },
  {
    id: 'quiz-math-012',
    subject: 'Mathematics',
    lessonId: 'math-012',
    type: 'mcq',
    question: 'What time is shown on a clock with the hour hand at 3 and minute hand at 12?',
    options: ['3:00', '12:03', '3:12', '12:30'],
    correctAnswer: 0,
    explanation: 'When the minute hand is at 12, it is on the hour. The hour hand at 3 means 3:00.',
    difficulty: 'easy',
  },

  // SCIENCE QUIZZES (12 questions)
  {
    id: 'quiz-sci-001',
    subject: 'Science',
    lessonId: 'sci-001',
    type: 'true-false',
    question: 'A rock is a living thing.',
    options: ['True', 'False'],
    correctAnswer: 1,
    explanation: 'False. A rock is non-living. It does not grow, move, or reproduce.',
    difficulty: 'easy',
  },
  {
    id: 'quiz-sci-002',
    subject: 'Science',
    lessonId: 'sci-002',
    type: 'mcq',
    question: 'What do plants need to grow?',
    options: ['Only water', 'Only sunlight', 'Water, sunlight, and soil', 'Only soil'],
    correctAnswer: 2,
    explanation: 'Plants need water, sunlight, and soil to grow properly.',
    difficulty: 'easy',
  },
  {
    id: 'quiz-sci-003',
    subject: 'Science',
    lessonId: 'sci-003',
    type: 'mcq',
    question: 'Which animal is a mammal?',
    options: ['Snake', 'Eagle', 'Dog', 'Butterfly'],
    correctAnswer: 2,
    explanation: 'Dogs are mammals. They have hair and feed milk to babies.',
    difficulty: 'easy',
  },
  {
    id: 'quiz-sci-004',
    subject: 'Science',
    lessonId: 'sci-004',
    type: 'mcq',
    question: 'In a food chain, what role do plants play?',
    options: ['Consumer', 'Producer', 'Decomposer', 'Predator'],
    correctAnswer: 1,
    explanation: 'Plants are producers. They make their own food using sunlight.',
    difficulty: 'medium',
  },
  {
    id: 'quiz-sci-005',
    subject: 'Science',
    lessonId: 'sci-005',
    type: 'mcq',
    question: 'What happens during evaporation in the water cycle?',
    options: ['Water freezes', 'Water becomes vapor', 'Water falls as rain', 'Water condenses'],
    correctAnswer: 1,
    explanation: 'Evaporation is when water becomes vapor and rises into the atmosphere.',
    difficulty: 'medium',
  },
  {
    id: 'quiz-sci-006',
    subject: 'Science',
    lessonId: 'sci-006',
    type: 'true-false',
    question: 'Weather and climate are the same thing.',
    options: ['True', 'False'],
    correctAnswer: 1,
    explanation: 'False. Weather is daily conditions. Climate is average weather over years.',
    difficulty: 'medium',
  },
  {
    id: 'quiz-sci-007',
    subject: 'Science',
    lessonId: 'sci-007',
    type: 'mcq',
    question: 'Which type of rock forms from cooled magma?',
    options: ['Sedimentary', 'Igneous', 'Metamorphic', 'Mineral'],
    correctAnswer: 1,
    explanation: 'Igneous rocks form from cooled magma.',
    difficulty: 'medium',
  },
  {
    id: 'quiz-sci-008',
    subject: 'Science',
    lessonId: 'sci-008',
    type: 'mcq',
    question: 'What is the state of matter of ice?',
    options: ['Liquid', 'Gas', 'Solid', 'Plasma'],
    correctAnswer: 2,
    explanation: 'Ice is solid water. It has a fixed shape and volume.',
    difficulty: 'easy',
  },
  {
    id: 'quiz-sci-009',
    subject: 'Science',
    lessonId: 'sci-009',
    type: 'true-false',
    question: 'A moving ball has kinetic energy.',
    options: ['True', 'False'],
    correctAnswer: 0,
    explanation: 'True. Kinetic energy is the energy of motion.',
    difficulty: 'medium',
  },
  {
    id: 'quiz-sci-010',
    subject: 'Science',
    lessonId: 'sci-010',
    type: 'mcq',
    question: 'Which travels faster, light or sound?',
    options: ['Sound', 'Light', 'They travel at the same speed', 'Neither travels'],
    correctAnswer: 1,
    explanation: 'Light travels much faster than sound.',
    difficulty: 'easy',
  },
  {
    id: 'quiz-sci-011',
    subject: 'Science',
    lessonId: 'sci-011',
    type: 'mcq',
    question: 'Which is a simple machine?',
    options: ['Computer', 'Lever', 'Bicycle', 'Car'],
    correctAnswer: 1,
    explanation: 'A lever is a simple machine. It helps us do work.',
    difficulty: 'easy',
  },
  {
    id: 'quiz-sci-012',
    subject: 'Science',
    lessonId: 'sci-012',
    type: 'mcq',
    question: 'How many planets are in our solar system?',
    options: ['7', '8', '9', '10'],
    correctAnswer: 1,
    explanation: 'There are 8 planets in our solar system.',
    difficulty: 'easy',
  },

  // ENGLISH QUIZZES (12 questions)
  {
    id: 'quiz-eng-001',
    subject: 'English',
    lessonId: 'eng-001',
    type: 'mcq',
    question: 'Which word is a noun?',
    options: ['Run', 'Happy', 'Dog', 'Quickly'],
    correctAnswer: 2,
    explanation: '"Dog" is a noun. It names a thing.',
    difficulty: 'easy',
  },
  {
    id: 'quiz-eng-002',
    subject: 'English',
    lessonId: 'eng-002',
    type: 'mcq',
    question: 'What is the past tense of "run"?',
    options: ['Runs', 'Running', 'Ran', 'Will run'],
    correctAnswer: 2,
    explanation: 'The past tense of "run" is "ran".',
    difficulty: 'easy',
  },
  {
    id: 'quiz-eng-003',
    subject: 'English',
    lessonId: 'eng-003',
    type: 'mcq',
    question: 'Which word is an adjective?',
    options: ['Run', 'Happy', 'Quickly', 'Dog'],
    correctAnswer: 1,
    explanation: '"Happy" is an adjective. It describes a noun.',
    difficulty: 'easy',
  },
  {
    id: 'quiz-eng-004',
    subject: 'English',
    lessonId: 'eng-004',
    type: 'mcq',
    question: 'Which sentence is correct?',
    options: ['She go to school', 'She goes to school', 'She going to school', 'She gone to school'],
    correctAnswer: 1,
    explanation: '"She goes to school" is correct. Present tense with third person needs "goes".',
    difficulty: 'medium',
  },
  {
    id: 'quiz-eng-005',
    subject: 'English',
    lessonId: 'eng-005',
    type: 'mcq',
    question: 'What is a synonym for "big"?',
    options: ['Small', 'Large', 'Tiny', 'Huge'],
    correctAnswer: 1,
    explanation: '"Large" is a synonym for "big". Both mean large in size.',
    difficulty: 'easy',
  },
  {
    id: 'quiz-eng-006',
    subject: 'English',
    lessonId: 'eng-006',
    type: 'mcq',
    question: 'What does the prefix "un-" mean?',
    options: ['Again', 'Not', 'Before', 'After'],
    correctAnswer: 1,
    explanation: 'The prefix "un-" means "not". Unhappy means not happy.',
    difficulty: 'medium',
  },
  {
    id: 'quiz-eng-007',
    subject: 'English',
    lessonId: 'eng-007',
    type: 'mcq',
    question: 'What is the main idea of a text?',
    options: ['A small detail', 'The most important point', 'A supporting fact', 'An example'],
    correctAnswer: 1,
    explanation: 'The main idea is the most important point of the text.',
    difficulty: 'medium',
  },
  {
    id: 'quiz-eng-008',
    subject: 'English',
    lessonId: 'eng-008',
    type: 'mcq',
    question: 'If a text says "She wore a heavy coat," what can you infer?',
    options: ['It was hot', 'It was cold', 'She was going swimming', 'She was going to bed'],
    correctAnswer: 1,
    explanation: 'If she wore a heavy coat, you can infer it was cold.',
    difficulty: 'medium',
  },
  {
    id: 'quiz-eng-009',
    subject: 'English',
    lessonId: 'eng-009',
    type: 'true-false',
    question: 'A paragraph should have only one main idea.',
    options: ['True', 'False'],
    correctAnswer: 0,
    explanation: 'True. A good paragraph focuses on one main idea.',
    difficulty: 'medium',
  },
  {
    id: 'quiz-eng-010',
    subject: 'English',
    lessonId: 'eng-010',
    type: 'mcq',
    question: 'What is the first part of a story called?',
    options: ['Middle', 'End', 'Beginning', 'Climax'],
    correctAnswer: 2,
    explanation: 'The beginning introduces characters and setting.',
    difficulty: 'easy',
  },
  {
    id: 'quiz-eng-011',
    subject: 'English',
    lessonId: 'eng-011',
    type: 'true-false',
    question: 'Good listeners make eye contact and ask questions.',
    options: ['True', 'False'],
    correctAnswer: 0,
    explanation: 'True. These are signs of active listening.',
    difficulty: 'easy',
  },
  {
    id: 'quiz-eng-012',
    subject: 'English',
    lessonId: 'eng-012',
    type: 'mcq',
    question: 'What is a fable?',
    options: ['A true story', 'A short story with animals that teaches a lesson', 'A very long book', 'A story about real people'],
    correctAnswer: 1,
    explanation: 'A fable is a short story with animals that teaches a moral lesson.',
    difficulty: 'easy',
  },

  // CODING QUIZZES (12 questions)
  {
    id: 'quiz-code-001',
    subject: 'Coding',
    lessonId: 'code-001',
    type: 'mcq',
    question: 'What is an algorithm?',
    options: ['A programming language', 'A step-by-step plan to solve a problem', 'A computer', 'A type of error'],
    correctAnswer: 1,
    explanation: 'An algorithm is a step-by-step plan to solve a problem.',
    difficulty: 'easy',
  },
  {
    id: 'quiz-code-002',
    subject: 'Coding',
    lessonId: 'code-002',
    type: 'mcq',
    question: 'Which data type stores text?',
    options: ['Integer', 'String', 'Boolean', 'Float'],
    correctAnswer: 1,
    explanation: 'A string stores text. Example: "Hello"',
    difficulty: 'easy',
  },
  {
    id: 'quiz-code-003',
    subject: 'Coding',
    lessonId: 'code-003',
    type: 'mcq',
    question: 'What does the + operator do?',
    options: ['Subtract', 'Add', 'Multiply', 'Divide'],
    correctAnswer: 1,
    explanation: 'The + operator adds two numbers.',
    difficulty: 'easy',
  },
  {
    id: 'quiz-code-004',
    subject: 'Coding',
    lessonId: 'code-004',
    type: 'true-false',
    question: 'An if statement makes decisions in code.',
    options: ['True', 'False'],
    correctAnswer: 0,
    explanation: 'True. If statements check conditions and run code based on true/false.',
    difficulty: 'easy',
  },
  {
    id: 'quiz-code-005',
    subject: 'Coding',
    lessonId: 'code-005',
    type: 'mcq',
    question: 'What does a for loop do?',
    options: ['Makes a decision', 'Repeats code a set number of times', 'Stores data', 'Displays output'],
    correctAnswer: 1,
    explanation: 'A for loop repeats code a set number of times.',
    difficulty: 'medium',
  },
  {
    id: 'quiz-code-006',
    subject: 'Coding',
    lessonId: 'code-006',
    type: 'true-false',
    question: 'Functions help organize code and avoid repetition.',
    options: ['True', 'False'],
    correctAnswer: 0,
    explanation: 'True. Functions are reusable blocks of code.',
    difficulty: 'medium',
  },
  {
    id: 'quiz-code-007',
    subject: 'Coding',
    lessonId: 'code-007',
    type: 'mcq',
    question: 'What is a list?',
    options: ['A single value', 'A collection of values', 'A type of error', 'A programming language'],
    correctAnswer: 1,
    explanation: 'A list stores multiple values.',
    difficulty: 'medium',
  },
  {
    id: 'quiz-code-008',
    subject: 'Coding',
    lessonId: 'code-008',
    type: 'mcq',
    question: 'What is a dictionary?',
    options: ['A book of words', 'Key-value pairs', 'A list of numbers', 'A type of loop'],
    correctAnswer: 1,
    explanation: 'A dictionary stores data as key-value pairs.',
    difficulty: 'medium',
  },
  {
    id: 'quiz-code-009',
    subject: 'Coding',
    lessonId: 'code-009',
    type: 'mcq',
    question: 'What is debugging?',
    options: ['Writing code', 'Finding and fixing errors', 'Running a program', 'Creating variables'],
    correctAnswer: 1,
    explanation: 'Debugging is finding and fixing errors in code.',
    difficulty: 'medium',
  },
  {
    id: 'quiz-code-010',
    subject: 'Coding',
    lessonId: 'code-010',
    type: 'true-false',
    question: 'Real programs use only one concept.',
    options: ['True', 'False'],
    correctAnswer: 1,
    explanation: 'False. Real programs combine multiple concepts.',
    difficulty: 'medium',
  },

  { id: 'quiz-geo-001', subject: 'Geography', lessonId: 'geo-001', type: 'mcq', question: 'What does a map key explain?', options: ['The age of the map', 'The meaning of symbols', 'The weather tomorrow', 'The population only'], correctAnswer: 1, explanation: 'A map key or legend explains the symbols and colours used on a map.', difficulty: 'easy' },
  { id: 'quiz-geo-002', subject: 'Geography', lessonId: 'geo-002', type: 'true-false', question: 'The Equator divides Earth into the Northern and Southern Hemispheres.', options: ['True', 'False'], correctAnswer: 0, explanation: 'The Equator is an imaginary line around the middle of Earth.', difficulty: 'easy' },
  { id: 'quiz-geo-003', subject: 'Geography', lessonId: 'geo-003', type: 'mcq', question: 'Which is a physical feature?', options: ['Mountain', 'Road', 'School', 'Bridge'], correctAnswer: 0, explanation: 'A mountain is a natural physical feature.', difficulty: 'easy' },
  { id: 'quiz-hist-001', subject: 'History', lessonId: 'hist-001', type: 'mcq', question: 'What is a primary source?', options: ['Evidence made during the time studied', 'A modern fictional story', 'Only a textbook', 'A guess about the past'], correctAnswer: 0, explanation: 'A primary source was created during the period being studied, such as a letter, object or photograph.', difficulty: 'medium' },
  { id: 'quiz-hist-002', subject: 'History', lessonId: 'hist-002', type: 'true-false', question: 'A timeline arranges events in chronological order.', options: ['True', 'False'], correctAnswer: 0, explanation: 'Chronological order means arranging events by date or time.', difficulty: 'easy' },
  { id: 'quiz-hist-003', subject: 'History', lessonId: 'hist-003', type: 'mcq', question: 'Why do historians compare different sources?', options: ['To make the past simpler', 'To check evidence and viewpoints', 'To avoid dates', 'To replace all facts'], correctAnswer: 1, explanation: 'Comparing sources helps historians check reliability and understand different viewpoints.', difficulty: 'medium' },
  { id: 'quiz-tamil-001', subject: 'Tamil', lessonId: 'tamil-001', type: 'mcq', question: 'Which letter is a Tamil vowel (உயிரெழுத்து)?', options: ['அ', 'க்', 'த்', 'ப்'], correctAnswer: 0, explanation: 'அ is one of the 12 Tamil உயிரெழுத்துகள்.', difficulty: 'easy' },
  { id: 'quiz-tamil-002', subject: 'Tamil', lessonId: 'tamil-002', type: 'mcq', question: 'What does “மரம்” mean?', options: ['Water', 'Tree', 'House', 'Book'], correctAnswer: 1, explanation: 'மரம் means tree.', difficulty: 'easy' },
  { id: 'quiz-tamil-003', subject: 'Tamil', lessonId: 'tamil-003', type: 'true-false', question: '“நான் படிக்கிறேன்” means “I am reading.”', options: ['True', 'False'], correctAnswer: 0, explanation: 'The sentence means “I am reading.”', difficulty: 'medium' },
  { id: 'quiz-music-001', subject: 'Music', lessonId: 'music-001', type: 'mcq', question: 'What is the steady pulse in music called?', options: ['Beat', 'Verse', 'Instrument', 'Volume'], correctAnswer: 0, explanation: 'The beat is the steady pulse of music.', difficulty: 'easy' },
  { id: 'quiz-music-002', subject: 'Music', lessonId: 'music-002', type: 'true-false', question: 'Pitch describes how high or low a sound is.', options: ['True', 'False'], correctAnswer: 0, explanation: 'Pitch is the quality that makes a sound seem high or low.', difficulty: 'easy' },
  { id: 'quiz-music-003', subject: 'Music', lessonId: 'music-003', type: 'mcq', question: 'Which instrument belongs to the percussion family?', options: ['Violin', 'Flute', 'Drum', 'Trumpet'], correctAnswer: 2, explanation: 'A drum is played by striking and belongs to the percussion family.', difficulty: 'easy' },
  { id: 'quiz-arts-001', subject: 'Arts', lessonId: 'arts-001', type: 'mcq', question: 'What colour is made by mixing yellow and blue paint?', options: ['Orange', 'Green', 'Purple', 'Brown'], correctAnswer: 1, explanation: 'Yellow and blue paint mix to make green.', difficulty: 'easy' },
  { id: 'quiz-arts-002', subject: 'Arts', lessonId: 'arts-002', type: 'true-false', question: 'Basic shapes can help plan a complex drawing.', options: ['True', 'False'], correctAnswer: 0, explanation: 'Artists often use simple shapes to plan structure before adding detail.', difficulty: 'easy' },
  { id: 'quiz-arts-003', subject: 'Arts', lessonId: 'arts-003', type: 'mcq', question: 'Which part of a picture usually appears farthest away?', options: ['Foreground', 'Background', 'Frame', 'Outline'], correctAnswer: 1, explanation: 'The background appears farthest from the viewer.', difficulty: 'medium' },
  { id: 'quiz-life-001', subject: 'Life Skills', lessonId: 'life-skills-001', type: 'mcq', question: 'Which action shows active listening?', options: ['Interrupting', 'Looking away', 'Asking a relevant question', 'Changing the subject'], correctAnswer: 2, explanation: 'A relevant follow-up question shows attention and interest.', difficulty: 'easy' },
  { id: 'quiz-life-002', subject: 'Life Skills', lessonId: 'life-skills-002', type: 'mcq', question: 'What is a good first step when planning study time?', options: ['Choose a clear goal', 'Open every book', 'Skip breaks', 'Study without a plan'], correctAnswer: 0, explanation: 'A clear, realistic goal gives the study session direction.', difficulty: 'easy' },
  { id: 'quiz-life-003', subject: 'Life Skills', lessonId: 'life-skills-003', type: 'true-false', question: 'Pausing and naming an emotion can help you choose a safer response.', options: ['True', 'False'], correctAnswer: 0, explanation: 'A calm pause helps create space for a thoughtful response.', difficulty: 'easy' },

];
