import type { QuizQuestion } from './quizzes'

export const supplementalQuizzes: QuizQuestion[] = [
  {
    id: 'quiz-math-013',
    subject: 'Mathematics',
    lessonId: 'math-013',
    type: 'mcq',
    question: 'Which type of graph is especially useful for showing change over time?',
    options: ['Pie chart', 'Line graph', 'Tally chart', 'Shape diagram'],
    correctAnswer: 1,
    explanation: 'A line graph connects values in order, making increases and decreases over time easy to see.',
    difficulty: 'medium',
  },
  {
    id: 'quiz-math-014',
    subject: 'Mathematics',
    lessonId: 'math-014',
    type: 'mcq',
    question: 'What should you do to find the total value of several coins and notes?',
    options: ['Subtract every value', 'Add all the values', 'Divide every value by two', 'Use only the largest value'],
    correctAnswer: 1,
    explanation: 'The total amount is found by adding the value of every coin and note together.',
    difficulty: 'easy',
  },
  {
    id: 'quiz-math-015',
    subject: 'Mathematics',
    lessonId: 'math-015',
    type: 'mcq',
    question: 'A box has 4 rows of 6 pencils. Which calculation finds the total number of pencils?',
    options: ['4 + 6', '6 - 4', '4 × 6', '6 ÷ 4'],
    correctAnswer: 2,
    explanation: 'Four equal rows of six are four groups of six, so multiplication gives 4 × 6 = 24.',
    difficulty: 'medium',
  },
  {
    id: 'quiz-geo-004',
    subject: 'Geography',
    lessonId: 'geo-004',
    type: 'mcq',
    question: 'What is the capital city of France?',
    options: ['Paris', 'Tokyo', 'Brasília', 'Cairo'],
    correctAnswer: 0,
    explanation: 'Paris is the capital city of France and is where the national government is based.',
    difficulty: 'easy',
  },
  {
    id: 'quiz-geo-005',
    subject: 'Geography',
    lessonId: 'geo-005',
    type: 'mcq',
    question: 'Which description best matches a tropical climate zone?',
    options: ['Very cold all year', 'Hot with substantial rainfall', 'Dry with no temperature changes', 'Four cold seasons'],
    correctAnswer: 1,
    explanation: 'Tropical climate zones are generally warm and receive substantial rainfall, supporting rainforests in many areas.',
    difficulty: 'medium',
  },
  {
    id: 'quiz-geo-006',
    subject: 'Geography',
    lessonId: 'geo-006',
    type: 'mcq',
    question: 'Which natural resource is non-renewable?',
    options: ['Wind', 'Sunlight', 'Coal', 'Trees grown sustainably'],
    correctAnswer: 2,
    explanation: 'Coal forms over a very long time and cannot be replaced quickly, so it is classed as non-renewable.',
    difficulty: 'medium',
  },
  {
    id: 'quiz-geo-007',
    subject: 'Geography',
    lessonId: 'geo-007',
    type: 'mcq',
    question: 'Which group contains examples of culture?',
    options: ['Language, food, art and traditions', 'Latitude, longitude, rainfall and soil', 'Mountains, rivers, valleys and plains', 'Roads, bridges, tunnels and airports only'],
    correctAnswer: 0,
    explanation: 'Culture includes the languages, foods, arts, beliefs, celebrations and traditions shared by groups of people.',
    difficulty: 'easy',
  },
  {
    id: 'quiz-geo-008',
    subject: 'Geography',
    lessonId: 'geo-008',
    type: 'mcq',
    question: 'What does urbanisation mean?',
    options: ['The growth of cities and urban populations', 'The movement of rivers', 'The formation of mountains', 'The cooling of polar regions'],
    correctAnswer: 0,
    explanation: 'Urbanisation is the growth of towns and cities as a larger share of people live in urban areas.',
    difficulty: 'medium',
  },
  {
    id: 'quiz-hist-004',
    subject: 'History',
    lessonId: 'hist-004',
    type: 'mcq',
    question: 'What did the Declaration of Independence announce?',
    options: ['The colonies would remain under British rule', 'The colonies claimed independence and stated their rights', 'Factories would replace farms', 'The First World War had ended'],
    correctAnswer: 1,
    explanation: 'The Declaration stated that the colonies claimed independence from Britain and set out principles about rights and government.',
    difficulty: 'medium',
  },
  {
    id: 'quiz-hist-005',
    subject: 'History',
    lessonId: 'hist-005',
    type: 'mcq',
    question: 'Which development helped power machines during the Industrial Revolution?',
    options: ['The steam engine', 'The compass rose', 'The printing of cave paintings', 'The stone hand axe'],
    correctAnswer: 0,
    explanation: 'Steam engines powered factory machinery, pumps and transport, helping production expand during the Industrial Revolution.',
    difficulty: 'medium',
  },
  {
    id: 'quiz-hist-006',
    subject: 'History',
    lessonId: 'hist-006',
    type: 'mcq',
    question: 'Which agreement is associated with formally ending World War I?',
    options: ['The Magna Carta', 'The Treaty of Versailles', 'The Declaration of Independence', 'The Civil Rights Act'],
    correctAnswer: 1,
    explanation: 'The Treaty of Versailles was signed in 1919 and was the principal peace treaty between Germany and the Allied powers after World War I.',
    difficulty: 'medium',
  },
  {
    id: 'quiz-hist-007',
    subject: 'History',
    lessonId: 'hist-007',
    type: 'mcq',
    question: 'During which years did World War II take place?',
    options: ['1775–1783', '1914–1918', '1939–1945', '1955–1968'],
    correctAnswer: 2,
    explanation: 'World War II began in 1939 and ended in 1945.',
    difficulty: 'easy',
  },
  {
    id: 'quiz-hist-008',
    subject: 'History',
    lessonId: 'hist-008',
    type: 'mcq',
    question: 'Which law is closely associated with ending legal segregation in the United States?',
    options: ['The Civil Rights Act of 1964', 'The Treaty of Versailles', 'The Factory Act of 1833', 'The Navigation Acts'],
    correctAnswer: 0,
    explanation: 'The Civil Rights Act of 1964 prohibited segregation in public places and banned discrimination in several areas of public life.',
    difficulty: 'medium',
  },
]
