import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(__dirname, '..')
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8')
const exists = (file) => fs.existsSync(path.join(root, file))
const existsAny = (...files) => files.some(exists)
const failures = []
const pass = (name) => console.log(`✓ ${name}`)
const check = (name, condition, detail = '') => condition ? pass(name) : failures.push(`${name}${detail ? `: ${detail}` : ''}`)

const index = read('index.html')
const app = read('src/app/App.tsx')
const header = read('src/components/Header.tsx')
const footer = read('src/components/Footer.tsx')
const storage = read('src/utils/storage.ts')
const familyControls = read('src/utils/familyControls.ts')
const mistakeBank = read('src/utils/mistakeBank.ts')
const learningNotes = read('src/utils/learningNotes.ts')
const settings = read('src/pages/Settings.tsx')
const platformHealth = read('src/pages/PlatformHealth.tsx')
const packageJson = JSON.parse(read('package.json'))
const shellText = [index, app, header, footer].join('\n')
const localModels = [storage, familyControls, mistakeBank, learningNotes].join('\n')

check('No Google Fonts network dependency', !/fonts\.googleapis\.com|fonts\.gstatic\.com/.test(index))
check('No analytics or advertising SDK references', !/google-analytics|googletagmanager|doubleclick|facebook\.net|segment\.com|mixpanel|hotjar/i.test([shellText, platformHealth].join('\n')))
check('Referrer policy is privacy preserving', /name="referrer" content="strict-origin-when-cross-origin"/.test(index))
check('Telephone detection is disabled', /format-detection" content="telephone=no"/.test(index))
check('Colour scheme metadata exists', /name="color-scheme"/.test(index))
check('Application name metadata exists', /name="application-name"/.test(index))
check('PWA manifest is linked', /rel="manifest"/.test(index))
check('App icon is linked', /rel="icon"/.test(index))
check('Accessible fallback landmark exists', /aria-label="ArivuKids loading and fallback experience"/.test(index))
check('No public child leaderboard claim in shell', !/public leaderboard|top students|global ranking/i.test(shellText))
check('No unsupported AI-powered claim in shell', !/AI-powered|powered by AI|artificial intelligence tutor/i.test(shellText))
check('Local-first wording is present', /local-first|current device/i.test([index, footer, localModels].join('\n')))
check('No child email field in local models', !/childEmail|learnerEmail|studentEmail/.test(localModels))
check('No child phone field in local models', !/childPhone|learnerPhone|studentPhone/.test(localModels))
check('No Aadhaar or APAAR field in local models', !/aadhaar|apaar/i.test(localModels))
check('No precise-location field in local models', !/latitude|longitude|geolocation|preciseLocation/i.test(localModels))
check('Family focus subjects are capped', /slice\(0, 3\)/.test(familyControls))
check('Timed sessions have finite retention', /SESSION_RETENTION_DAYS\s*=\s*90/.test(familyControls))
check('Timed sessions are locally stored', /kvs_learning_sessions/.test(familyControls) && /localStorage/.test(familyControls))
check('Mistake bank has finite retention', /MAX_RECORDS\s*=\s*200/.test(mistakeBank))
check('Learning notes have finite retention', /MAX_NOTES\s*=\s*100/.test(learningNotes))
check('Learning notes warn against sensitive data', /do not enter passwords/i.test(read('src/pages/LearningNotes.tsx')))
check('Import size validation exists', /1\s*MB|1_000_000|1024\s*\*\s*1024|max.*size/i.test(settings))
check('Data reset is confirmation protected', /prompt\(|confirm\(|confirmation/i.test(settings))
check('Root error boundary exists', exists('src/components/ErrorBoundary.tsx'))
check('Connectivity status component exists', exists('src/components/ConnectivityBanner.tsx'))
check('Route experience component exists', exists('src/components/RouteEffects.tsx'))
check('Controlled update notice exists', exists('src/components/AppUpdateNotice.tsx'))
check('Security policy exists', existsAny('public/security.html', 'security.html'))
check('security.txt exists', exists('public/.well-known/security.txt'))
check('robots.txt exists', existsAny('public/robots.txt', 'robots.txt'))
check('sitemap exists', existsAny('public/sitemap.xml', 'sitemap.xml'))
check('Privacy page exists', existsAny('public/privacy.html', 'privacy.html'))
check('Child-readable privacy page exists', exists('public/child-privacy.html'))
check('Accessibility statement exists', exists('public/accessibility.html'))
check('Data-retention explanation exists', exists('public/data-retention.html'))
check('Support and grievance guidance exists', exists('public/grievance.html'))
check('Parent guide exists', exists('public/parent-guide.html'))
check('Acceptable-use guidance exists', exists('public/acceptable-use.html'))
check('Device-storage explanation exists', exists('public/device-storage.html'))
check('Terms page exists', existsAny('public/terms.html', 'terms.html'))
check('Safety page exists', existsAny('public/safety.html', 'safety.html'))
check('Contact page exists', existsAny('public/contact.html', 'contact.html'))
check('No service worker dependency on external CDN', exists('public/sw.js') && !/https?:\/\//.test(read('public/sw.js')))
check('Platform diagnostics state that results are not uploaded', /not uploaded|not transmit/i.test(platformHealth))
check('Required trust validation script is registered', packageJson.scripts?.['validate:trust'] === 'node scripts/validate-trust.mjs')

if (failures.length) {
  console.error('\nTrust validation failed:')
  for (const failure of failures) console.error(`✗ ${failure}`)
  process.exit(1)
}
console.log('\n✓ Privacy, child-safety, family-control and ArivuKids release-integrity checks passed')
